import type { Csp } from '../../types'

const REACT_APP_ETHEREUM_NODE_URL = process.env.REACT_APP_ETHEREUM_NODE_URL
const REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL = process.env.REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL
const REACT_APP_UNCHAINED_ETHEREUM_WS_URL = process.env.REACT_APP_UNCHAINED_ETHEREUM_WS_URL
const REACT_APP_ALCHEMY_POLYGON_URL = process.env.REACT_APP_ALCHEMY_POLYGON_URL

if (!REACT_APP_ETHEREUM_NODE_URL) throw new Error('REACT_APP_ETHEREUM_NODE_URL is required')
if (!REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL)
  throw new Error('REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL is required')
if (!REACT_APP_UNCHAINED_ETHEREUM_WS_URL)
  throw new Error('REACT_APP_UNCHAINED_ETHEREUM_WS_URL is required')
if (!REACT_APP_ALCHEMY_POLYGON_URL) throw new Error('REACT_APP_ALCHEMY_POLYGON_URL is required')

export const csp: Csp = {
  'connect-src': [
    REACT_APP_ETHEREUM_NODE_URL,
    REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL,
    REACT_APP_UNCHAINED_ETHEREUM_WS_URL,
    REACT_APP_ALCHEMY_POLYGON_URL,
    'https://eth.llamarpc.com',
  ],
}
