import { IndexedAssetData } from '..'
import { Asset, BaseAsset, ChainTypes, ContractTypes, NetworkTypes } from '../types'

export const mockBaseAssets: BaseAsset[] = [
  {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true,
    tokens: [
      {
        name: 'Aave',
        precision: 18,
        tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        secondaryColor: '#FFFFFF',
        icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'AAVE'
      },
      {
        name: 'Fox',
        precision: 18,
        tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        secondaryColor: '#FFFFFF',
        icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'FOX'
      }
    ]
  },
  {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.TESTNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true,
    tokens: [
      {
        name: 'Fox',
        precision: 18,
        tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        secondaryColor: '#FFFFFF',
        icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'FOX'
      }
    ]
  },
  {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.MAINNET, // <---------- mainnet
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.TESTNET, // <---------- testnet
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockAssets: Asset[] = [
  {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    name: 'Aave',
    precision: 18,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.TESTNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.TESTNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockIndexedAssetData: IndexedAssetData = {
  ethereum_MAINNET: {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_MAINNET_0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9: {
    name: 'Aave',
    precision: 18,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_MAINNET_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_TESTNET: {
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.TESTNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_TESTNET_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.TESTNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  bitcoin_MAINNET: {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  bitcoin_TESTNET: {
    chain: ChainTypes.Bitcoin,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
}
