import {
  Asset,
  AssetDataSource,
  BaseAsset,
  ChainTypes,
  ContractTypes,
  NetworkTypes
} from '@shapeshiftoss/types'

import { IndexedAssetData } from '..'

export const mockBaseAssets: BaseAsset[] = [
  {
    caip19: 'eip155:1/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true,
    tokens: [
      {
        caip19: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
        name: 'Aave',
        precision: 18,
        tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        dataSource: AssetDataSource.CoinGecko,
        secondaryColor: '#FFFFFF',
        icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'AAVE'
      },
      {
        caip19: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
        name: 'Fox',
        precision: 18,
        tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        dataSource: AssetDataSource.CoinGecko,
        secondaryColor: '#FFFFFF',
        icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'FOX'
      }
    ]
  },
  {
    caip19: 'eip155:3/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true,
    tokens: [
      {
        caip19: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
        name: 'Fox',
        precision: 18,
        tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
        contractType: ContractTypes.ERC20,
        color: '#FFFFFF',
        secondaryColor: '#FFFFFF',
        dataSource: AssetDataSource.CoinGecko,
        icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'FOX'
      }
    ]
  },
  {
    caip19: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  {
    caip19: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockAssets: Asset[] = [
  {
    caip19: 'eip155:1/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    caip19: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    name: 'Aave',
    precision: 18,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    dataSource: AssetDataSource.CoinGecko,
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    caip19: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    caip19: 'eip155:3/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    caip19: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.ETH_ROPSTEN,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  {
    caip19: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  {
    caip19: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockIndexedAssetData: IndexedAssetData = {
  ethereum_MAINNET: {
    caip19: 'eip155:1/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_MAINNET_0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9: {
    caip19: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    name: 'Aave',
    precision: 18,
    dataSource: AssetDataSource.CoinGecko,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_MAINNET_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    caip19: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_ETH_ROPSTEN: {
    caip19: 'eip155:3/slip44:60',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_ETH_ROPSTEN_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    caip19: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: ContractTypes.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.ETH_ROPSTEN,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  bitcoin_MAINNET: {
    caip19: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    sendSupport: false,
    receiveSupport: false
  },
  bitcoin_TESTNET: {
    caip19: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    sendSupport: false,
    receiveSupport: false
  }
}
