import { AssetNamespace } from '@shapeshiftoss/caip'
import { Asset, AssetDataSource, BaseAsset, ChainTypes, NetworkTypes } from '@shapeshiftoss/types'

import { IndexedAssetData } from '..'

export const ETHMockedAsset: BaseAsset = {
  assetId: 'eip155:1/slip44:60',
  chainId: 'eip155:1',
  chain: ChainTypes.Ethereum,
  dataSource: AssetDataSource.CoinGecko,
  network: NetworkTypes.MAINNET,
  symbol: 'ETH',
  name: 'Ethereum',
  precision: 18,
  slip44: 60,
  color: '#FFFFFF',
  secondaryColor: '#FFFFFF',
  icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
  explorer: 'https://etherscan.io',
  explorerTxLink: 'https://etherscan.io/tx/',
  explorerAddressLink: 'https://etherscan.io/address/',
  sendSupport: true,
  receiveSupport: true,
  tokens: [
    {
      assetId: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
      chainId: 'eip155:1',
      name: 'Aave',
      precision: 18,
      tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
      contractType: AssetNamespace.ERC20,
      color: '#FFFFFF',
      dataSource: AssetDataSource.CoinGecko,
      secondaryColor: '#FFFFFF',
      icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
      sendSupport: true,
      receiveSupport: true,
      symbol: 'AAVE'
    },
    {
      assetId: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
      chainId: 'eip155:1',
      name: 'Fox',
      precision: 18,
      tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
      contractType: AssetNamespace.ERC20,
      color: '#FFFFFF',
      dataSource: AssetDataSource.CoinGecko,
      secondaryColor: '#FFFFFF',
      icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
      sendSupport: true,
      receiveSupport: true,
      symbol: 'FOX'
    }
  ]
}

export const BTCMockedAsset: BaseAsset = {
  assetId: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
  chainId: 'bip122:000000000019d6689c085ae165831e93',
  chain: ChainTypes.Bitcoin,
  dataSource: AssetDataSource.CoinGecko,
  network: NetworkTypes.MAINNET,
  symbol: 'BTC',
  name: 'Bitcoin',
  precision: 8,
  slip44: 0,
  color: '#FFFFFF',
  secondaryColor: '#FFFFFF',
  icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
  explorer: 'https://live.blockcypher.com',
  explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
  explorerAddressLink: 'https://live.blockcypher.com/btc/address/',
  sendSupport: false,
  receiveSupport: false
}

export const mockBaseAssets: BaseAsset[] = [
  ETHMockedAsset,
  {
    assetId: 'eip155:3/slip44:60',
    chainId: 'eip155:3',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/',
    sendSupport: true,
    receiveSupport: true,
    tokens: [
      {
        assetId: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
        chainId: 'eip155:3',
        name: 'Fox',
        precision: 18,
        tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
        contractType: AssetNamespace.ERC20,
        color: '#FFFFFF',
        secondaryColor: '#FFFFFF',
        dataSource: AssetDataSource.CoinGecko,
        icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
        sendSupport: true,
        receiveSupport: true,
        symbol: 'FOX'
      }
    ]
  },
  BTCMockedAsset,
  {
    assetId: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chainId: 'bip122:000000000933ea01ad0ee984209779ba',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    explorerAddressLink: 'https://live.blockcypher.com/btc-testnet/address/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockAssets: Asset[] = [
  {
    assetId: 'eip155:1/slip44:60',
    chainId: 'eip155:1',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    assetId: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    chainId: 'eip155:1',
    name: 'Aave',
    precision: 18,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    dataSource: AssetDataSource.CoinGecko,
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/'
  },
  {
    assetId: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    chainId: 'eip155:1',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/'
  },
  {
    assetId: 'eip155:3/slip44:60',
    chainId: 'eip155:3',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/',
    sendSupport: true,
    receiveSupport: true
  },
  {
    assetId: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    chainId: 'eip155:3',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.ETH_ROPSTEN,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/'
  },
  {
    assetId: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    chainId: 'bip122:000000000019d6689c085ae165831e93',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    explorerAddressLink: 'https://live.blockcypher.com/btc/address/',
    sendSupport: false,
    receiveSupport: false
  },
  {
    assetId: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chainId: 'bip122:000000000933ea01ad0ee984209779ba',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    explorerAddressLink: 'https://live.blockcypher.com/btc-testnet/address/',
    sendSupport: false,
    receiveSupport: false
  }
]

export const mockIndexedAssetData: IndexedAssetData = {
  ethereum_MAINNET: {
    assetId: 'eip155:1/slip44:60',
    chainId: 'eip155:1',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_MAINNET_0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9: {
    assetId: 'eip155:1/erc20:0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    chainId: 'eip155:1',
    name: 'Aave',
    precision: 18,
    dataSource: AssetDataSource.CoinGecko,
    tokenId: '0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9',
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coingecko.com/coins/images/12645/thumb/AAVE.png?1601374110',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'AAVE',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerAddressLink: 'https://etherscan.io/address/',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_MAINNET_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    assetId: 'eip155:1/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    chainId: 'eip155:1',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.MAINNET,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerAddressLink: 'https://etherscan.io/address/',
    explorerTxLink: 'https://etherscan.io/tx/'
  },
  ethereum_ETH_ROPSTEN: {
    assetId: 'eip155:3/slip44:60',
    chainId: 'eip155:3',
    chain: ChainTypes.Ethereum,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.ETH_ROPSTEN,
    symbol: 'ETH',
    name: 'Ethereum',
    precision: 18,
    slip44: 60,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/eth@2x.png',
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/',
    sendSupport: true,
    receiveSupport: true
  },
  ethereum_ETH_ROPSTEN_0xc770eefad204b5180df6a14ee197d99d808ee52d: {
    assetId: 'eip155:3/erc20:0xc770eefad204b5180df6a14ee197d99d808ee52d',
    chainId: 'eip155:3',
    name: 'Fox',
    precision: 18,
    tokenId: '0xc770eefad204b5180df6a14ee197d99d808ee52d',
    dataSource: AssetDataSource.CoinGecko,
    contractType: AssetNamespace.ERC20,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/fox@2x.png',
    sendSupport: true,
    receiveSupport: true,
    symbol: 'FOX',
    chain: ChainTypes.Ethereum,
    network: NetworkTypes.ETH_ROPSTEN,
    slip44: 60,
    explorer: 'https://etherscan.io',
    explorerTxLink: 'https://etherscan.io/tx/',
    explorerAddressLink: 'https://etherscan.io/address/'
  },
  bitcoin_MAINNET: {
    assetId: 'bip122:000000000019d6689c085ae165831e93/slip44:0',
    chainId: 'bip122:000000000019d6689c085ae165831e93',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.MAINNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 0,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com',
    explorerTxLink: 'https://live.blockcypher.com/btc/tx/',
    explorerAddressLink: 'https://live.blockcypher.com/btc/address/',
    sendSupport: false,
    receiveSupport: false
  },
  bitcoin_TESTNET: {
    assetId: 'bip122:000000000933ea01ad0ee984209779ba/slip44:0',
    chainId: 'bip122:000000000933ea01ad0ee984209779ba',
    chain: ChainTypes.Bitcoin,
    dataSource: AssetDataSource.CoinGecko,
    network: NetworkTypes.TESTNET,
    symbol: 'BTC',
    name: 'Bitcoin',
    precision: 8,
    slip44: 1,
    color: '#FFFFFF',
    secondaryColor: '#FFFFFF',
    icon: 'https://assets.coincap.io/assets/icons/btc@2x.png',
    explorer: 'https://live.blockcypher.com/btc-testnet/',
    explorerTxLink: 'https://live.blockcypher.com/btc-testnet/tx/',
    explorerAddressLink: 'https://live.blockcypher.com/btc-testnet/address/',
    sendSupport: false,
    receiveSupport: false
  }
}
