enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

preferInteractive: true

progressBarStyle: hogsfather

yarnPath: .yarn/releases/yarn-3.2.3.cjs
