export enum KeyManager {
  Mobile = 'mobile',
  Native = 'native',
  Coinbase = 'coinbase',
  Phantom = 'phantom',
  Seeker = 'seeker',
  MetaMask = 'metamask',
  KeepKey = 'keepkey',
  Keplr = 'keplr',
  WalletConnectV2 = 'walletconnectv2',
  Ledger = 'ledger',
  Trezor = 'trezor',
  Vultisig = 'vultisig',
  GridPlus = 'gridplus',
}
