// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusPaidFee
 */
export interface ChainflipBaasStatusPaidFee {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusPaidFee
     */
    readonly type?: ChainflipBaasStatusPaidFeeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusPaidFee
     */
    readonly asset?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusPaidFee
     */
    readonly amountNative?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusPaidFee
     */
    readonly amount?: number;
}


/**
 * @export
 */
export const ChainflipBaasStatusPaidFeeTypeEnum = {
    Network: 'network',
    Ingress: 'ingress',
    Egress: 'egress',
    Broker: 'broker',
    Boost: 'boost',
    Liquidity: 'liquidity'
} as const;
export type ChainflipBaasStatusPaidFeeTypeEnum = typeof ChainflipBaasStatusPaidFeeTypeEnum[keyof typeof ChainflipBaasStatusPaidFeeTypeEnum];


/**
 * Check if a given object implements the ChainflipBaasStatusPaidFee interface.
 */
export function instanceOfChainflipBaasStatusPaidFee(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusPaidFeeFromJSON(json: any): ChainflipBaasStatusPaidFee {
    return ChainflipBaasStatusPaidFeeFromJSONTyped(json, false);
}

export function ChainflipBaasStatusPaidFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusPaidFee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'asset': !exists(json, 'asset') ? undefined : json['asset'],
        'amountNative': !exists(json, 'amountNative') ? undefined : json['amountNative'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
    };
}

export function ChainflipBaasStatusPaidFeeToJSON(value?: ChainflipBaasStatusPaidFee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

