// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasQuotePoolFee } from './ChainflipBaasQuotePoolFee';
import {
    ChainflipBaasQuotePoolFeeFromJSON,
    ChainflipBaasQuotePoolFeeFromJSONTyped,
    ChainflipBaasQuotePoolFeeToJSON,
} from './ChainflipBaasQuotePoolFee';

/**
 * 
 * @export
 * @interface ChainflipBaasQuotePoolInfo
 */
export interface ChainflipBaasQuotePoolInfo {
    /**
     * The base asset of the pool involved.
     * @type {string}
     * @memberof ChainflipBaasQuotePoolInfo
     */
    baseAsset?: string;
    /**
     * The quote asset of the pool involved.
     * @type {string}
     * @memberof ChainflipBaasQuotePoolInfo
     */
    quoteAsset?: string;
    /**
     * 
     * @type {ChainflipBaasQuotePoolFee}
     * @memberof ChainflipBaasQuotePoolInfo
     */
    fee?: ChainflipBaasQuotePoolFee;
}

/**
 * Check if a given object implements the ChainflipBaasQuotePoolInfo interface.
 */
export function instanceOfChainflipBaasQuotePoolInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasQuotePoolInfoFromJSON(json: any): ChainflipBaasQuotePoolInfo {
    return ChainflipBaasQuotePoolInfoFromJSONTyped(json, false);
}

export function ChainflipBaasQuotePoolInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasQuotePoolInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'baseAsset': !exists(json, 'baseAsset') ? undefined : json['baseAsset'],
        'quoteAsset': !exists(json, 'quoteAsset') ? undefined : json['quoteAsset'],
        'fee': !exists(json, 'fee') ? undefined : ChainflipBaasQuotePoolFeeFromJSON(json['fee']),
    };
}

export function ChainflipBaasQuotePoolInfoToJSON(value?: ChainflipBaasQuotePoolInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'baseAsset': value.baseAsset,
        'quoteAsset': value.quoteAsset,
        'fee': ChainflipBaasQuotePoolFeeToJSON(value.fee),
    };
}

