// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasQuotePoolFee
 */
export interface ChainflipBaasQuotePoolFee {
    /**
     * The asset the fee is processed in.
     * @type {string}
     * @memberof ChainflipBaasQuotePoolFee
     */
    asset?: string | null;
    /**
     * The fee amount.
     * @type {number}
     * @memberof ChainflipBaasQuotePoolFee
     */
    amount?: number;
    /**
     * The fee amount in native units.
     * @type {string}
     * @memberof ChainflipBaasQuotePoolFee
     */
    amountNative?: string;
}

/**
 * Check if a given object implements the ChainflipBaasQuotePoolFee interface.
 */
export function instanceOfChainflipBaasQuotePoolFee(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasQuotePoolFeeFromJSON(json: any): ChainflipBaasQuotePoolFee {
    return ChainflipBaasQuotePoolFeeFromJSONTyped(json, false);
}

export function ChainflipBaasQuotePoolFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasQuotePoolFee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'asset': !exists(json, 'asset') ? undefined : json['asset'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'amountNative': !exists(json, 'amountNative') ? undefined : json['amountNative'],
    };
}

export function ChainflipBaasQuotePoolFeeToJSON(value?: ChainflipBaasQuotePoolFee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'asset': value.asset,
        'amount': value.amount,
        'amountNative': value.amountNative,
    };
}

