// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusBoost } from './ChainflipBaasStatusBoost';
import {
    ChainflipBaasStatusBoostFromJSON,
    ChainflipBaasStatusBoostFromJSONTyped,
    ChainflipBaasStatusBoostToJSON,
} from './ChainflipBaasStatusBoost';
import type { ChainflipBaasStatusCcmParameters } from './ChainflipBaasStatusCcmParameters';
import {
    ChainflipBaasStatusCcmParametersFromJSON,
    ChainflipBaasStatusCcmParametersFromJSONTyped,
    ChainflipBaasStatusCcmParametersToJSON,
} from './ChainflipBaasStatusCcmParameters';
import type { ChainflipBaasStatusDeposit } from './ChainflipBaasStatusDeposit';
import {
    ChainflipBaasStatusDepositFromJSON,
    ChainflipBaasStatusDepositFromJSONTyped,
    ChainflipBaasStatusDepositToJSON,
} from './ChainflipBaasStatusDeposit';
import type { ChainflipBaasStatusDepositChannel } from './ChainflipBaasStatusDepositChannel';
import {
    ChainflipBaasStatusDepositChannelFromJSON,
    ChainflipBaasStatusDepositChannelFromJSONTyped,
    ChainflipBaasStatusDepositChannelToJSON,
} from './ChainflipBaasStatusDepositChannel';
import type { ChainflipBaasStatusEgress } from './ChainflipBaasStatusEgress';
import {
    ChainflipBaasStatusEgressFromJSON,
    ChainflipBaasStatusEgressFromJSONTyped,
    ChainflipBaasStatusEgressToJSON,
} from './ChainflipBaasStatusEgress';
import type { ChainflipBaasStatusPaidFee } from './ChainflipBaasStatusPaidFee';
import {
    ChainflipBaasStatusPaidFeeFromJSON,
    ChainflipBaasStatusPaidFeeFromJSONTyped,
    ChainflipBaasStatusPaidFeeToJSON,
} from './ChainflipBaasStatusPaidFee';
import type { ChainflipBaasStatusSwap } from './ChainflipBaasStatusSwap';
import {
    ChainflipBaasStatusSwapFromJSON,
    ChainflipBaasStatusSwapFromJSONTyped,
    ChainflipBaasStatusSwapToJSON,
} from './ChainflipBaasStatusSwap';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusSwapStatus
 */
export interface ChainflipBaasStatusSwapStatus {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly state?: ChainflipBaasStatusSwapStatusStateEnum;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly swapId?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly sourceAsset?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly destinationAsset?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly destinationAddress?: string;
    /**
     * 
     * @type {ChainflipBaasStatusDepositChannel}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    depositChannel?: ChainflipBaasStatusDepositChannel;
    /**
     * 
     * @type {ChainflipBaasStatusCcmParameters}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    ccmParams?: ChainflipBaasStatusCcmParameters;
    /**
     * 
     * @type {ChainflipBaasStatusBoost}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    boost?: ChainflipBaasStatusBoost;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly estimatedDurationSeconds?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly sourceChainRequiredBlockConfirmations?: number | null;
    /**
     * 
     * @type {Array<ChainflipBaasStatusPaidFee>}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly fees?: Array<ChainflipBaasStatusPaidFee> | null;
    /**
     * 
     * @type {ChainflipBaasStatusDeposit}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    deposit?: ChainflipBaasStatusDeposit;
    /**
     * 
     * @type {ChainflipBaasStatusSwap}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    swap?: ChainflipBaasStatusSwap;
    /**
     * 
     * @type {ChainflipBaasStatusEgress}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    swapEgress?: ChainflipBaasStatusEgress;
    /**
     * 
     * @type {ChainflipBaasStatusEgress}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    refundEgress?: ChainflipBaasStatusEgress;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly lastStateChainUpdateAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusSwapStatus
     */
    readonly lastStateChainUpdateAtDate?: Date | null;
}


/**
 * @export
 */
export const ChainflipBaasStatusSwapStatusStateEnum = {
    Waiting: 'waiting',
    Receiving: 'receiving',
    Swapping: 'swapping',
    Sending: 'sending',
    Sent: 'sent',
    Completed: 'completed',
    Failed: 'failed'
} as const;
export type ChainflipBaasStatusSwapStatusStateEnum = typeof ChainflipBaasStatusSwapStatusStateEnum[keyof typeof ChainflipBaasStatusSwapStatusStateEnum];


/**
 * Check if a given object implements the ChainflipBaasStatusSwapStatus interface.
 */
export function instanceOfChainflipBaasStatusSwapStatus(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusSwapStatusFromJSON(json: any): ChainflipBaasStatusSwapStatus {
    return ChainflipBaasStatusSwapStatusFromJSONTyped(json, false);
}

export function ChainflipBaasStatusSwapStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusSwapStatus {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'state': !exists(json, 'state') ? undefined : json['state'],
        'swapId': !exists(json, 'swapId') ? undefined : json['swapId'],
        'sourceAsset': !exists(json, 'sourceAsset') ? undefined : json['sourceAsset'],
        'destinationAsset': !exists(json, 'destinationAsset') ? undefined : json['destinationAsset'],
        'destinationAddress': !exists(json, 'destinationAddress') ? undefined : json['destinationAddress'],
        'depositChannel': !exists(json, 'depositChannel') ? undefined : ChainflipBaasStatusDepositChannelFromJSON(json['depositChannel']),
        'ccmParams': !exists(json, 'ccmParams') ? undefined : ChainflipBaasStatusCcmParametersFromJSON(json['ccmParams']),
        'boost': !exists(json, 'boost') ? undefined : ChainflipBaasStatusBoostFromJSON(json['boost']),
        'estimatedDurationSeconds': !exists(json, 'estimatedDurationSeconds') ? undefined : json['estimatedDurationSeconds'],
        'sourceChainRequiredBlockConfirmations': !exists(json, 'sourceChainRequiredBlockConfirmations') ? undefined : json['sourceChainRequiredBlockConfirmations'],
        'fees': !exists(json, 'fees') ? undefined : (json['fees'] === null ? null : (json['fees'] as Array<any>).map(ChainflipBaasStatusPaidFeeFromJSON)),
        'deposit': !exists(json, 'deposit') ? undefined : ChainflipBaasStatusDepositFromJSON(json['deposit']),
        'swap': !exists(json, 'swap') ? undefined : ChainflipBaasStatusSwapFromJSON(json['swap']),
        'swapEgress': !exists(json, 'swapEgress') ? undefined : ChainflipBaasStatusEgressFromJSON(json['swapEgress']),
        'refundEgress': !exists(json, 'refundEgress') ? undefined : ChainflipBaasStatusEgressFromJSON(json['refundEgress']),
        'lastStateChainUpdateAt': !exists(json, 'lastStateChainUpdateAt') ? undefined : json['lastStateChainUpdateAt'],
        'lastStateChainUpdateAtDate': !exists(json, 'lastStateChainUpdateAtDate') ? undefined : (json['lastStateChainUpdateAtDate'] === null ? null : new Date(json['lastStateChainUpdateAtDate'])),
    };
}

export function ChainflipBaasStatusSwapStatusToJSON(value?: ChainflipBaasStatusSwapStatus | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'depositChannel': ChainflipBaasStatusDepositChannelToJSON(value.depositChannel),
        'ccmParams': ChainflipBaasStatusCcmParametersToJSON(value.ccmParams),
        'boost': ChainflipBaasStatusBoostToJSON(value.boost),
        'deposit': ChainflipBaasStatusDepositToJSON(value.deposit),
        'swap': ChainflipBaasStatusSwapToJSON(value.swap),
        'swapEgress': ChainflipBaasStatusEgressToJSON(value.swapEgress),
        'refundEgress': ChainflipBaasStatusEgressToJSON(value.refundEgress),
    };
}

