// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasQuoteBoostQuote } from './ChainflipBaasQuoteBoostQuote';
import {
    ChainflipBaasQuoteBoostQuoteFromJSON,
    ChainflipBaasQuoteBoostQuoteFromJSONTyped,
    ChainflipBaasQuoteBoostQuoteToJSON,
} from './ChainflipBaasQuoteBoostQuote';
import type { ChainflipBaasQuoteEstimatedDurationsSeconds } from './ChainflipBaasQuoteEstimatedDurationsSeconds';
import {
    ChainflipBaasQuoteEstimatedDurationsSecondsFromJSON,
    ChainflipBaasQuoteEstimatedDurationsSecondsFromJSONTyped,
    ChainflipBaasQuoteEstimatedDurationsSecondsToJSON,
} from './ChainflipBaasQuoteEstimatedDurationsSeconds';
import type { ChainflipBaasQuotePoolInfo } from './ChainflipBaasQuotePoolInfo';
import {
    ChainflipBaasQuotePoolInfoFromJSON,
    ChainflipBaasQuotePoolInfoFromJSONTyped,
    ChainflipBaasQuotePoolInfoToJSON,
} from './ChainflipBaasQuotePoolInfo';
import type { ChainflipBaasQuoteQuoteFee } from './ChainflipBaasQuoteQuoteFee';
import {
    ChainflipBaasQuoteQuoteFeeFromJSON,
    ChainflipBaasQuoteQuoteFeeFromJSONTyped,
    ChainflipBaasQuoteQuoteFeeToJSON,
} from './ChainflipBaasQuoteQuoteFee';

/**
 * 
 * @export
 * @interface ChainflipBaasQuoteQuote
 */
export interface ChainflipBaasQuoteQuote {
    /**
     * The type of quote.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly type?: ChainflipBaasQuoteQuoteTypeEnum;
    /**
     * The asset to send.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    ingressAsset?: string;
    /**
     * The amount to send.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    ingressAmount?: number;
    /**
     * The amount to send in native units.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly ingressAmountNative?: string;
    /**
     * The asset used as intermediary.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    intermediateAsset?: string | null;
    /**
     * The amount used as intermediary.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly intermediateAmount?: number | null;
    /**
     * The amount used as intermediary in native units.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly intermediateAmountNative?: string | null;
    /**
     * The asset to receive.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    egressAsset?: string;
    /**
     * The amount to receive.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly egressAmount?: number;
    /**
     * The amount to receive in native units.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly egressAmountNative?: string;
    /**
     * The fee structure, this includes all fees.
     * @type {Array<ChainflipBaasQuoteQuoteFee>}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly includedFees?: Array<ChainflipBaasQuoteQuoteFee>;
    /**
     * Recommended slippage percentage to use when calculating minimum price.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly recommendedSlippageTolerancePercent?: number;
    /**
     * A warning in case liquidity is low and there is a risk of high slippage.
     * @type {boolean}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly lowLiquidityWarning?: boolean;
    /**
     * Liquidity pools involved in the swap, as well as estimated liquidity provider fees.
     * @type {Array<ChainflipBaasQuotePoolInfo>}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly poolInfo?: Array<ChainflipBaasQuotePoolInfo>;
    /**
     * The estimated time the swap will take.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly estimatedDurationSeconds?: number;
    /**
     * 
     * @type {ChainflipBaasQuoteEstimatedDurationsSeconds}
     * @memberof ChainflipBaasQuoteQuote
     */
    estimatedDurationsSeconds?: ChainflipBaasQuoteEstimatedDurationsSeconds;
    /**
     * The estimated price in the destination asset for 1 unit of the source asset. Used for slippage calculations.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly estimatedPrice?: number;
    /**
     * The number of "sub-swaps" to perform for a DCA swap.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly chunkIntervalBlocks?: number | null;
    /**
     * The delay between the "sub-swaps" of a DCA swap in number of blocks.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuote
     */
    readonly numberOfChunks?: number | null;
    /**
     * 
     * @type {ChainflipBaasQuoteBoostQuote}
     * @memberof ChainflipBaasQuoteQuote
     */
    boostQuote?: ChainflipBaasQuoteBoostQuote;
}


/**
 * @export
 */
export const ChainflipBaasQuoteQuoteTypeEnum = {
    Regular: 'regular',
    Dca: 'dca'
} as const;
export type ChainflipBaasQuoteQuoteTypeEnum = typeof ChainflipBaasQuoteQuoteTypeEnum[keyof typeof ChainflipBaasQuoteQuoteTypeEnum];


/**
 * Check if a given object implements the ChainflipBaasQuoteQuote interface.
 */
export function instanceOfChainflipBaasQuoteQuote(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasQuoteQuoteFromJSON(json: any): ChainflipBaasQuoteQuote {
    return ChainflipBaasQuoteQuoteFromJSONTyped(json, false);
}

export function ChainflipBaasQuoteQuoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasQuoteQuote {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'ingressAsset': !exists(json, 'ingressAsset') ? undefined : json['ingressAsset'],
        'ingressAmount': !exists(json, 'ingressAmount') ? undefined : json['ingressAmount'],
        'ingressAmountNative': !exists(json, 'ingressAmountNative') ? undefined : json['ingressAmountNative'],
        'intermediateAsset': !exists(json, 'intermediateAsset') ? undefined : json['intermediateAsset'],
        'intermediateAmount': !exists(json, 'intermediateAmount') ? undefined : json['intermediateAmount'],
        'intermediateAmountNative': !exists(json, 'intermediateAmountNative') ? undefined : json['intermediateAmountNative'],
        'egressAsset': !exists(json, 'egressAsset') ? undefined : json['egressAsset'],
        'egressAmount': !exists(json, 'egressAmount') ? undefined : json['egressAmount'],
        'egressAmountNative': !exists(json, 'egressAmountNative') ? undefined : json['egressAmountNative'],
        'includedFees': !exists(json, 'includedFees') ? undefined : ((json['includedFees'] as Array<any>).map(ChainflipBaasQuoteQuoteFeeFromJSON)),
        'recommendedSlippageTolerancePercent': !exists(json, 'recommendedSlippageTolerancePercent') ? undefined : json['recommendedSlippageTolerancePercent'],
        'lowLiquidityWarning': !exists(json, 'lowLiquidityWarning') ? undefined : json['lowLiquidityWarning'],
        'poolInfo': !exists(json, 'poolInfo') ? undefined : ((json['poolInfo'] as Array<any>).map(ChainflipBaasQuotePoolInfoFromJSON)),
        'estimatedDurationSeconds': !exists(json, 'estimatedDurationSeconds') ? undefined : json['estimatedDurationSeconds'],
        'estimatedDurationsSeconds': !exists(json, 'estimatedDurationsSeconds') ? undefined : ChainflipBaasQuoteEstimatedDurationsSecondsFromJSON(json['estimatedDurationsSeconds']),
        'estimatedPrice': !exists(json, 'estimatedPrice') ? undefined : json['estimatedPrice'],
        'chunkIntervalBlocks': !exists(json, 'chunkIntervalBlocks') ? undefined : json['chunkIntervalBlocks'],
        'numberOfChunks': !exists(json, 'numberOfChunks') ? undefined : json['numberOfChunks'],
        'boostQuote': !exists(json, 'boostQuote') ? undefined : ChainflipBaasQuoteBoostQuoteFromJSON(json['boostQuote']),
    };
}

export function ChainflipBaasQuoteQuoteToJSON(value?: ChainflipBaasQuoteQuote | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ingressAsset': value.ingressAsset,
        'ingressAmount': value.ingressAmount,
        'intermediateAsset': value.intermediateAsset,
        'egressAsset': value.egressAsset,
        'estimatedDurationsSeconds': ChainflipBaasQuoteEstimatedDurationsSecondsToJSON(value.estimatedDurationsSeconds),
        'boostQuote': ChainflipBaasQuoteBoostQuoteToJSON(value.boostQuote),
    };
}

