// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusBoost
 */
export interface ChainflipBaasStatusBoost {
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly maximumBoostFeeBps?: number;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly effectiveBoostFeeBps?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly boostedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly boostedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly boostedBlockIndex?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly skippedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly skippedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusBoost
     */
    readonly skippedBlockIndex?: string | null;
}

/**
 * Check if a given object implements the ChainflipBaasStatusBoost interface.
 */
export function instanceOfChainflipBaasStatusBoost(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusBoostFromJSON(json: any): ChainflipBaasStatusBoost {
    return ChainflipBaasStatusBoostFromJSONTyped(json, false);
}

export function ChainflipBaasStatusBoostFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusBoost {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'maximumBoostFeeBps': !exists(json, 'maximumBoostFeeBps') ? undefined : json['maximumBoostFeeBps'],
        'effectiveBoostFeeBps': !exists(json, 'effectiveBoostFeeBps') ? undefined : json['effectiveBoostFeeBps'],
        'boostedAt': !exists(json, 'boostedAt') ? undefined : json['boostedAt'],
        'boostedAtDate': !exists(json, 'boostedAtDate') ? undefined : (json['boostedAtDate'] === null ? null : new Date(json['boostedAtDate'])),
        'boostedBlockIndex': !exists(json, 'boostedBlockIndex') ? undefined : json['boostedBlockIndex'],
        'skippedAt': !exists(json, 'skippedAt') ? undefined : json['skippedAt'],
        'skippedAtDate': !exists(json, 'skippedAtDate') ? undefined : (json['skippedAtDate'] === null ? null : new Date(json['skippedAtDate'])),
        'skippedBlockIndex': !exists(json, 'skippedBlockIndex') ? undefined : json['skippedBlockIndex'],
    };
}

export function ChainflipBaasStatusBoostToJSON(value?: ChainflipBaasStatusBoost | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

