// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusFailure } from './ChainflipBaasStatusFailure';
import {
    ChainflipBaasStatusFailureFromJSON,
    ChainflipBaasStatusFailureFromJSONTyped,
    ChainflipBaasStatusFailureToJSON,
} from './ChainflipBaasStatusFailure';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusDeposit
 */
export interface ChainflipBaasStatusDeposit {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly amountNative?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly amount?: number;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly transactionReference?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly transactionConfirmations?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly witnessedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly witnessedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly witnessedBlockIndex?: string | null;
    /**
     * 
     * @type {ChainflipBaasStatusFailure}
     * @memberof ChainflipBaasStatusDeposit
     */
    failure?: ChainflipBaasStatusFailure;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly failedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly failedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDeposit
     */
    readonly failedBlockIndex?: string | null;
}

/**
 * Check if a given object implements the ChainflipBaasStatusDeposit interface.
 */
export function instanceOfChainflipBaasStatusDeposit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusDepositFromJSON(json: any): ChainflipBaasStatusDeposit {
    return ChainflipBaasStatusDepositFromJSONTyped(json, false);
}

export function ChainflipBaasStatusDepositFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusDeposit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountNative': !exists(json, 'amountNative') ? undefined : json['amountNative'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'transactionReference': !exists(json, 'transactionReference') ? undefined : json['transactionReference'],
        'transactionConfirmations': !exists(json, 'transactionConfirmations') ? undefined : json['transactionConfirmations'],
        'witnessedAt': !exists(json, 'witnessedAt') ? undefined : json['witnessedAt'],
        'witnessedAtDate': !exists(json, 'witnessedAtDate') ? undefined : (json['witnessedAtDate'] === null ? null : new Date(json['witnessedAtDate'])),
        'witnessedBlockIndex': !exists(json, 'witnessedBlockIndex') ? undefined : json['witnessedBlockIndex'],
        'failure': !exists(json, 'failure') ? undefined : ChainflipBaasStatusFailureFromJSON(json['failure']),
        'failedAt': !exists(json, 'failedAt') ? undefined : json['failedAt'],
        'failedAtDate': !exists(json, 'failedAtDate') ? undefined : (json['failedAtDate'] === null ? null : new Date(json['failedAtDate'])),
        'failedBlockIndex': !exists(json, 'failedBlockIndex') ? undefined : json['failedBlockIndex'],
    };
}

export function ChainflipBaasStatusDepositToJSON(value?: ChainflipBaasStatusDeposit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'failure': ChainflipBaasStatusFailureToJSON(value.failure),
    };
}

