// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusAffiliateBroker
 */
export interface ChainflipBaasStatusAffiliateBroker {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusAffiliateBroker
     */
    readonly account?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusAffiliateBroker
     */
    readonly commissionBps?: number;
}

/**
 * Check if a given object implements the ChainflipBaasStatusAffiliateBroker interface.
 */
export function instanceOfChainflipBaasStatusAffiliateBroker(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusAffiliateBrokerFromJSON(json: any): ChainflipBaasStatusAffiliateBroker {
    return ChainflipBaasStatusAffiliateBrokerFromJSONTyped(json, false);
}

export function ChainflipBaasStatusAffiliateBrokerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusAffiliateBroker {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'account': !exists(json, 'account') ? undefined : json['account'],
        'commissionBps': !exists(json, 'commissionBps') ? undefined : json['commissionBps'],
    };
}

export function ChainflipBaasStatusAffiliateBrokerToJSON(value?: ChainflipBaasStatusAffiliateBroker | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

