// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusReason
 */
export interface ChainflipBaasStatusReason {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusReason
     */
    readonly code?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusReason
     */
    readonly message?: string;
}

/**
 * Check if a given object implements the ChainflipBaasStatusReason interface.
 */
export function instanceOfChainflipBaasStatusReason(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusReasonFromJSON(json: any): ChainflipBaasStatusReason {
    return ChainflipBaasStatusReasonFromJSONTyped(json, false);
}

export function ChainflipBaasStatusReasonFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusReason {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': !exists(json, 'code') ? undefined : json['code'],
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ChainflipBaasStatusReasonToJSON(value?: ChainflipBaasStatusReason | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

