// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasSwapCcmRequest } from './ChainflipBaasSwapCcmRequest';
import {
    ChainflipBaasSwapCcmRequestFromJSON,
    ChainflipBaasSwapCcmRequestFromJSONTyped,
    ChainflipBaasSwapCcmRequestToJSON,
} from './ChainflipBaasSwapCcmRequest';

/**
 * 
 * @export
 * @interface ChainflipBaasSwapAdvancedSwapRequest
 */
export interface ChainflipBaasSwapAdvancedSwapRequest {
    /**
     * 
     * @type {ChainflipBaasSwapCcmRequest}
     * @memberof ChainflipBaasSwapAdvancedSwapRequest
     */
    ccmPayload?: ChainflipBaasSwapCcmRequest;
}

/**
 * Check if a given object implements the ChainflipBaasSwapAdvancedSwapRequest interface.
 */
export function instanceOfChainflipBaasSwapAdvancedSwapRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasSwapAdvancedSwapRequestFromJSON(json: any): ChainflipBaasSwapAdvancedSwapRequest {
    return ChainflipBaasSwapAdvancedSwapRequestFromJSONTyped(json, false);
}

export function ChainflipBaasSwapAdvancedSwapRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasSwapAdvancedSwapRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ccmPayload': !exists(json, 'ccmPayload') ? undefined : ChainflipBaasSwapCcmRequestFromJSON(json['ccmPayload']),
    };
}

export function ChainflipBaasSwapAdvancedSwapRequestToJSON(value?: ChainflipBaasSwapAdvancedSwapRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ccmPayload': ChainflipBaasSwapCcmRequestToJSON(value.ccmPayload),
    };
}

