// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Cross-Chain Messaging payload. More details can be found at https://docs.chainflip.io/swapping/integrations/advanced/cross-chain-messaging/cross-chain-messaging
 * @export
 * @interface ChainflipBaasSwapCcmRequest
 */
export interface ChainflipBaasSwapCcmRequest {
    /**
     * Gas budget for the call on the destination chain. This amount is based on the source asset and will be subtracted from the input amount and swapped to pay for gas.
     * @type {string}
     * @memberof ChainflipBaasSwapCcmRequest
     */
    gasBudget: string;
    /**
     * Hex-encoded message that is passed to the destination address on the destination chain. The message should be shorter than 10k bytes.
     * @type {string}
     * @memberof ChainflipBaasSwapCcmRequest
     */
    message: string;
}

/**
 * Check if a given object implements the ChainflipBaasSwapCcmRequest interface.
 */
export function instanceOfChainflipBaasSwapCcmRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "gasBudget" in value;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ChainflipBaasSwapCcmRequestFromJSON(json: any): ChainflipBaasSwapCcmRequest {
    return ChainflipBaasSwapCcmRequestFromJSONTyped(json, false);
}

export function ChainflipBaasSwapCcmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasSwapCcmRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'gasBudget': json['gas_budget'],
        'message': json['message'],
    };
}

export function ChainflipBaasSwapCcmRequestToJSON(value?: ChainflipBaasSwapCcmRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'gas_budget': value.gasBudget,
        'message': value.message,
    };
}

