// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasQuoteEstimatedDurationsSeconds
 */
export interface ChainflipBaasQuoteEstimatedDurationsSeconds {
    /**
     * The estimated time for a deposit to be witnessed.
     * @type {number}
     * @memberof ChainflipBaasQuoteEstimatedDurationsSeconds
     */
    readonly deposit?: number;
    /**
     * The estimated time for a swap to be fully executed.
     * @type {number}
     * @memberof ChainflipBaasQuoteEstimatedDurationsSeconds
     */
    readonly swap?: number;
    /**
     * The estimated time until the output transaction is included in a block.
     * @type {number}
     * @memberof ChainflipBaasQuoteEstimatedDurationsSeconds
     */
    readonly egress?: number;
}

/**
 * Check if a given object implements the ChainflipBaasQuoteEstimatedDurationsSeconds interface.
 */
export function instanceOfChainflipBaasQuoteEstimatedDurationsSeconds(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasQuoteEstimatedDurationsSecondsFromJSON(json: any): ChainflipBaasQuoteEstimatedDurationsSeconds {
    return ChainflipBaasQuoteEstimatedDurationsSecondsFromJSONTyped(json, false);
}

export function ChainflipBaasQuoteEstimatedDurationsSecondsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasQuoteEstimatedDurationsSeconds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deposit': !exists(json, 'deposit') ? undefined : json['deposit'],
        'swap': !exists(json, 'swap') ? undefined : json['swap'],
        'egress': !exists(json, 'egress') ? undefined : json['egress'],
    };
}

export function ChainflipBaasQuoteEstimatedDurationsSecondsToJSON(value?: ChainflipBaasQuoteEstimatedDurationsSeconds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

