// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusSwapStatus } from './ChainflipBaasStatusSwapStatus';
import {
    ChainflipBaasStatusSwapStatusFromJSON,
    ChainflipBaasStatusSwapStatusFromJSONTyped,
    ChainflipBaasStatusSwapStatusToJSON,
} from './ChainflipBaasStatusSwapStatus';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusStatusResponse
 */
export interface ChainflipBaasStatusStatusResponse {
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusStatusResponse
     */
    id?: number;
    /**
     * 
     * @type {ChainflipBaasStatusSwapStatus}
     * @memberof ChainflipBaasStatusStatusResponse
     */
    status?: ChainflipBaasStatusSwapStatus;
}

/**
 * Check if a given object implements the ChainflipBaasStatusStatusResponse interface.
 */
export function instanceOfChainflipBaasStatusStatusResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusStatusResponseFromJSON(json: any): ChainflipBaasStatusStatusResponse {
    return ChainflipBaasStatusStatusResponseFromJSONTyped(json, false);
}

export function ChainflipBaasStatusStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusStatusResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : ChainflipBaasStatusSwapStatusFromJSON(json['status']),
    };
}

export function ChainflipBaasStatusStatusResponseToJSON(value?: ChainflipBaasStatusStatusResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': ChainflipBaasStatusSwapStatusToJSON(value.status),
    };
}

