// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusFillOrKillParameters
 */
export interface ChainflipBaasStatusFillOrKillParameters {
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusFillOrKillParameters
     */
    readonly retryDurationBlocks?: number;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusFillOrKillParameters
     */
    readonly refundAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusFillOrKillParameters
     */
    readonly minimumPrice?: string;
}

/**
 * Check if a given object implements the ChainflipBaasStatusFillOrKillParameters interface.
 */
export function instanceOfChainflipBaasStatusFillOrKillParameters(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusFillOrKillParametersFromJSON(json: any): ChainflipBaasStatusFillOrKillParameters {
    return ChainflipBaasStatusFillOrKillParametersFromJSONTyped(json, false);
}

export function ChainflipBaasStatusFillOrKillParametersFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusFillOrKillParameters {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'retryDurationBlocks': !exists(json, 'retryDurationBlocks') ? undefined : json['retryDurationBlocks'],
        'refundAddress': !exists(json, 'refundAddress') ? undefined : json['refundAddress'],
        'minimumPrice': !exists(json, 'minimumPrice') ? undefined : json['minimumPrice'],
    };
}

export function ChainflipBaasStatusFillOrKillParametersToJSON(value?: ChainflipBaasStatusFillOrKillParameters | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

