// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusFailure } from './ChainflipBaasStatusFailure';
import {
    ChainflipBaasStatusFailureFromJSON,
    ChainflipBaasStatusFailureFromJSONTyped,
    ChainflipBaasStatusFailureToJSON,
} from './ChainflipBaasStatusFailure';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusEgress
 */
export interface ChainflipBaasStatusEgress {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly amountNative?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly amount?: number;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly scheduledAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly scheduledAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly scheduledBlockIndex?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly transactionReference?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly witnessedAt?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly witnessedBlockIndex?: string | null;
    /**
     * 
     * @type {ChainflipBaasStatusFailure}
     * @memberof ChainflipBaasStatusEgress
     */
    failure?: ChainflipBaasStatusFailure;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly failedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly failedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusEgress
     */
    readonly failedBlockIndex?: string | null;
}

/**
 * Check if a given object implements the ChainflipBaasStatusEgress interface.
 */
export function instanceOfChainflipBaasStatusEgress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusEgressFromJSON(json: any): ChainflipBaasStatusEgress {
    return ChainflipBaasStatusEgressFromJSONTyped(json, false);
}

export function ChainflipBaasStatusEgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusEgress {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amountNative': !exists(json, 'amountNative') ? undefined : json['amountNative'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'scheduledAt': !exists(json, 'scheduledAt') ? undefined : json['scheduledAt'],
        'scheduledAtDate': !exists(json, 'scheduledAtDate') ? undefined : (json['scheduledAtDate'] === null ? null : new Date(json['scheduledAtDate'])),
        'scheduledBlockIndex': !exists(json, 'scheduledBlockIndex') ? undefined : json['scheduledBlockIndex'],
        'transactionReference': !exists(json, 'transactionReference') ? undefined : json['transactionReference'],
        'witnessedAt': !exists(json, 'witnessedAt') ? undefined : json['witnessedAt'],
        'witnessedBlockIndex': !exists(json, 'witnessedBlockIndex') ? undefined : json['witnessedBlockIndex'],
        'failure': !exists(json, 'failure') ? undefined : ChainflipBaasStatusFailureFromJSON(json['failure']),
        'failedAt': !exists(json, 'failedAt') ? undefined : json['failedAt'],
        'failedAtDate': !exists(json, 'failedAtDate') ? undefined : (json['failedAtDate'] === null ? null : new Date(json['failedAtDate'])),
        'failedBlockIndex': !exists(json, 'failedBlockIndex') ? undefined : json['failedBlockIndex'],
    };
}

export function ChainflipBaasStatusEgressToJSON(value?: ChainflipBaasStatusEgress | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'failure': ChainflipBaasStatusFailureToJSON(value.failure),
    };
}

