// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusAffiliateBroker } from './ChainflipBaasStatusAffiliateBroker';
import {
    ChainflipBaasStatusAffiliateBrokerFromJSON,
    ChainflipBaasStatusAffiliateBrokerFromJSONTyped,
    ChainflipBaasStatusAffiliateBrokerToJSON,
} from './ChainflipBaasStatusAffiliateBroker';
import type { ChainflipBaasStatusDcaParameters } from './ChainflipBaasStatusDcaParameters';
import {
    ChainflipBaasStatusDcaParametersFromJSON,
    ChainflipBaasStatusDcaParametersFromJSONTyped,
    ChainflipBaasStatusDcaParametersToJSON,
} from './ChainflipBaasStatusDcaParameters';
import type { ChainflipBaasStatusFillOrKillParameters } from './ChainflipBaasStatusFillOrKillParameters';
import {
    ChainflipBaasStatusFillOrKillParametersFromJSON,
    ChainflipBaasStatusFillOrKillParametersFromJSONTyped,
    ChainflipBaasStatusFillOrKillParametersToJSON,
} from './ChainflipBaasStatusFillOrKillParameters';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusDepositChannel
 */
export interface ChainflipBaasStatusDepositChannel {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly id?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly createdAt?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly createdAtDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly brokerCommissionBps?: number;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly depositAddress?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly sourceChainExpiryBlock?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly estimatedExpiryTime?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly estimatedExpiryDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly expectedDepositAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly expectedDepositAmountNative?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly isExpired?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly openedThroughBackend?: boolean;
    /**
     * 
     * @type {Array<ChainflipBaasStatusAffiliateBroker>}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    readonly affiliateBrokers?: Array<ChainflipBaasStatusAffiliateBroker> | null;
    /**
     * 
     * @type {ChainflipBaasStatusFillOrKillParameters}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    fillOrKillParams?: ChainflipBaasStatusFillOrKillParameters;
    /**
     * 
     * @type {ChainflipBaasStatusDcaParameters}
     * @memberof ChainflipBaasStatusDepositChannel
     */
    dcaParams?: ChainflipBaasStatusDcaParameters;
}

/**
 * Check if a given object implements the ChainflipBaasStatusDepositChannel interface.
 */
export function instanceOfChainflipBaasStatusDepositChannel(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusDepositChannelFromJSON(json: any): ChainflipBaasStatusDepositChannel {
    return ChainflipBaasStatusDepositChannelFromJSONTyped(json, false);
}

export function ChainflipBaasStatusDepositChannelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusDepositChannel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'createdAtDate': !exists(json, 'createdAtDate') ? undefined : (new Date(json['createdAtDate'])),
        'brokerCommissionBps': !exists(json, 'brokerCommissionBps') ? undefined : json['brokerCommissionBps'],
        'depositAddress': !exists(json, 'depositAddress') ? undefined : json['depositAddress'],
        'sourceChainExpiryBlock': !exists(json, 'sourceChainExpiryBlock') ? undefined : json['sourceChainExpiryBlock'],
        'estimatedExpiryTime': !exists(json, 'estimatedExpiryTime') ? undefined : json['estimatedExpiryTime'],
        'estimatedExpiryDate': !exists(json, 'estimatedExpiryDate') ? undefined : (new Date(json['estimatedExpiryDate'])),
        'expectedDepositAmount': !exists(json, 'expectedDepositAmount') ? undefined : json['expectedDepositAmount'],
        'expectedDepositAmountNative': !exists(json, 'expectedDepositAmountNative') ? undefined : json['expectedDepositAmountNative'],
        'isExpired': !exists(json, 'isExpired') ? undefined : json['isExpired'],
        'openedThroughBackend': !exists(json, 'openedThroughBackend') ? undefined : json['openedThroughBackend'],
        'affiliateBrokers': !exists(json, 'affiliateBrokers') ? undefined : (json['affiliateBrokers'] === null ? null : (json['affiliateBrokers'] as Array<any>).map(ChainflipBaasStatusAffiliateBrokerFromJSON)),
        'fillOrKillParams': !exists(json, 'fillOrKillParams') ? undefined : ChainflipBaasStatusFillOrKillParametersFromJSON(json['fillOrKillParams']),
        'dcaParams': !exists(json, 'dcaParams') ? undefined : ChainflipBaasStatusDcaParametersFromJSON(json['dcaParams']),
    };
}

export function ChainflipBaasStatusDepositChannelToJSON(value?: ChainflipBaasStatusDepositChannel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fillOrKillParams': ChainflipBaasStatusFillOrKillParametersToJSON(value.fillOrKillParams),
        'dcaParams': ChainflipBaasStatusDcaParametersToJSON(value.dcaParams),
    };
}

