// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasStatusChunkInfo
 */
export interface ChainflipBaasStatusChunkInfo {
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly inputAmountNative?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly inputAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly intermediateAmountNative?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly intermediateAmount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly outputAmountNative?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly outputAmount?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly scheduledAt?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly scheduledAtDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly scheduledBlockIndex?: string;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly executedAt?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly executedAtDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly executedBlockIndex?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusChunkInfo
     */
    readonly retryCount?: number;
}

/**
 * Check if a given object implements the ChainflipBaasStatusChunkInfo interface.
 */
export function instanceOfChainflipBaasStatusChunkInfo(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusChunkInfoFromJSON(json: any): ChainflipBaasStatusChunkInfo {
    return ChainflipBaasStatusChunkInfoFromJSONTyped(json, false);
}

export function ChainflipBaasStatusChunkInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusChunkInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'inputAmountNative': !exists(json, 'inputAmountNative') ? undefined : json['inputAmountNative'],
        'inputAmount': !exists(json, 'inputAmount') ? undefined : json['inputAmount'],
        'intermediateAmountNative': !exists(json, 'intermediateAmountNative') ? undefined : json['intermediateAmountNative'],
        'intermediateAmount': !exists(json, 'intermediateAmount') ? undefined : json['intermediateAmount'],
        'outputAmountNative': !exists(json, 'outputAmountNative') ? undefined : json['outputAmountNative'],
        'outputAmount': !exists(json, 'outputAmount') ? undefined : json['outputAmount'],
        'scheduledAt': !exists(json, 'scheduledAt') ? undefined : json['scheduledAt'],
        'scheduledAtDate': !exists(json, 'scheduledAtDate') ? undefined : (new Date(json['scheduledAtDate'])),
        'scheduledBlockIndex': !exists(json, 'scheduledBlockIndex') ? undefined : json['scheduledBlockIndex'],
        'executedAt': !exists(json, 'executedAt') ? undefined : json['executedAt'],
        'executedAtDate': !exists(json, 'executedAtDate') ? undefined : (json['executedAtDate'] === null ? null : new Date(json['executedAtDate'])),
        'executedBlockIndex': !exists(json, 'executedBlockIndex') ? undefined : json['executedBlockIndex'],
        'retryCount': !exists(json, 'retryCount') ? undefined : json['retryCount'],
    };
}

export function ChainflipBaasStatusChunkInfoToJSON(value?: ChainflipBaasStatusChunkInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

