// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChainflipBaasQuoteQuoteFee
 */
export interface ChainflipBaasQuoteQuoteFee {
    /**
     * The type of fee.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuoteFee
     */
    readonly type?: ChainflipBaasQuoteQuoteFeeTypeEnum;
    /**
     * The asset the fee is processed in.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuoteFee
     */
    readonly asset?: string | null;
    /**
     * The fee amount.
     * @type {number}
     * @memberof ChainflipBaasQuoteQuoteFee
     */
    readonly amount?: number;
    /**
     * The fee amount in native units.
     * @type {string}
     * @memberof ChainflipBaasQuoteQuoteFee
     */
    readonly amountNative?: string;
}


/**
 * @export
 */
export const ChainflipBaasQuoteQuoteFeeTypeEnum = {
    Ingress: 'ingress',
    Broker: 'broker',
    Network: 'network',
    Liquidity: 'liquidity',
    Egress: 'egress',
    Boost: 'boost'
} as const;
export type ChainflipBaasQuoteQuoteFeeTypeEnum = typeof ChainflipBaasQuoteQuoteFeeTypeEnum[keyof typeof ChainflipBaasQuoteQuoteFeeTypeEnum];


/**
 * Check if a given object implements the ChainflipBaasQuoteQuoteFee interface.
 */
export function instanceOfChainflipBaasQuoteQuoteFee(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasQuoteQuoteFeeFromJSON(json: any): ChainflipBaasQuoteQuoteFee {
    return ChainflipBaasQuoteQuoteFeeFromJSONTyped(json, false);
}

export function ChainflipBaasQuoteQuoteFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasQuoteQuoteFee {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'asset': !exists(json, 'asset') ? undefined : json['asset'],
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'amountNative': !exists(json, 'amountNative') ? undefined : json['amountNative'],
    };
}

export function ChainflipBaasQuoteQuoteFeeToJSON(value?: ChainflipBaasQuoteQuoteFee | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

