// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Chainflip Broker as a Service
 * Run your own Chainflip Broker without any hassle.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ChainflipBaasStatusReason } from './ChainflipBaasStatusReason';
import {
    ChainflipBaasStatusReasonFromJSON,
    ChainflipBaasStatusReasonFromJSONTyped,
    ChainflipBaasStatusReasonToJSON,
} from './ChainflipBaasStatusReason';

/**
 * 
 * @export
 * @interface ChainflipBaasStatusFailure
 */
export interface ChainflipBaasStatusFailure {
    /**
     * 
     * @type {number}
     * @memberof ChainflipBaasStatusFailure
     */
    readonly failedAt?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChainflipBaasStatusFailure
     */
    readonly failedAtDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusFailure
     */
    readonly failedBlockIndex?: string;
    /**
     * 
     * @type {string}
     * @memberof ChainflipBaasStatusFailure
     */
    readonly mode?: string;
    /**
     * 
     * @type {ChainflipBaasStatusReason}
     * @memberof ChainflipBaasStatusFailure
     */
    reason?: ChainflipBaasStatusReason;
}

/**
 * Check if a given object implements the ChainflipBaasStatusFailure interface.
 */
export function instanceOfChainflipBaasStatusFailure(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ChainflipBaasStatusFailureFromJSON(json: any): ChainflipBaasStatusFailure {
    return ChainflipBaasStatusFailureFromJSONTyped(json, false);
}

export function ChainflipBaasStatusFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChainflipBaasStatusFailure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'failedAt': !exists(json, 'failedAt') ? undefined : json['failedAt'],
        'failedAtDate': !exists(json, 'failedAtDate') ? undefined : (new Date(json['failedAtDate'])),
        'failedBlockIndex': !exists(json, 'failedBlockIndex') ? undefined : json['failedBlockIndex'],
        'mode': !exists(json, 'mode') ? undefined : json['mode'],
        'reason': !exists(json, 'reason') ? undefined : ChainflipBaasStatusReasonFromJSON(json['reason']),
    };
}

export function ChainflipBaasStatusFailureToJSON(value?: ChainflipBaasStatusFailure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'reason': ChainflipBaasStatusReasonToJSON(value.reason),
    };
}

