// CJS environment file - uses process.env for Node.js environments
export const ENV = {
  VITE_AVALANCHE_NODE_URL: process.env.VITE_AVALANCHE_NODE_URL,
  VITE_OPTIMISM_NODE_URL: process.env.VITE_OPTIMISM_NODE_URL,
  VITE_BNBSMARTCHAIN_NODE_URL: process.env.VITE_BNBSMARTCHAIN_NODE_URL,
  VITE_POLYGON_NODE_URL: process.env.VITE_POLYGON_NODE_URL,
  VITE_GNOSIS_NODE_URL: process.env.VITE_GNOSIS_NODE_URL,
  VITE_ETHEREUM_NODE_URL: process.env.VITE_ETHEREUM_NODE_URL,
  VITE_ARBITRUM_NODE_URL: process.env.VITE_ARBITRUM_NODE_URL,
  VITE_ARBITRUM_NOVA_NODE_URL: process.env.VITE_ARBITRUM_NOVA_NODE_URL,
  VITE_BASE_NODE_URL: process.env.VITE_BASE_NODE_URL,
}
