export const FALLBACK_RPC_URLS = {
  // first class chains
  ethereum: ['https://ethereum-rpc.publicnode.com', 'https://eth.drpc.org'],
  bsc: ['https://bsc-rpc.publicnode.com', 'https://bsc.drpc.org'],
  avalanche: ['https://avalanche-c-chain-rpc.publicnode.com', 'https://avalanche.drpc.org'],
  arbitrum: ['https://arbitrum-one-rpc.publicnode.com', 'https://arbitrum.drpc.org'],
  optimism: ['https://optimism-rpc.publicnode.com', 'https://optimism.drpc.org'],
  gnosis: ['https://gnosis-rpc.publicnode.com', 'https://gnosis.drpc.org'],
  polygon: ['https://polygon-bor-rpc.publicnode.com', 'https://polygon.drpc.org'],
  base: ['https://base-rpc.publicnode.com', 'https://base.drpc.org'],
  // second class chains
  abstract: [
    'https://abstract.drpc.org',
    'https://abstract.api.onfinality.io/public',
    'https://abstract-mainnet.gateway.tatum.io',
  ],
  berachain: [
    'https://berachain-rpc.publicnode.com',
    'https://berachain.drpc.org',
    'https://berachain-mainnet.gateway.tatum.io',
  ],
  blast: ['https://blast-rpc.publicnode.com', 'https://blast.drpc.org'],
  bob: ['https://bob.drpc.org'],
  celo: [
    'https://celo.drpc.org',
    'https://celo.api.onfinality.io/public',
    'https://celo-mainnet.gateway.tatum.io',
  ],
  cronos: [
    'https://cronos-evm-rpc.publicnode.com',
    'https://cronos.drpc.org',
    'https://cro-mainnet.gateway.tatum.io',
  ],
  ethereal: [],
  flowEvm: ['https://flow-mainnet.gateway.tatum.io'],
  hemi: ['https://hemi.drpc.org'],
  hyperEvm: ['https://hyperliquid.drpc.org'],
  ink: ['https://rpc-qnd.inkonchain.com', 'https://ink.drpc.org'],
  katana: ['https://rpc.katanarpc.com', 'https://katana.drpc.org'],
  linea: ['https://linea-rpc.publicnode.com', 'https://linea.drpc.org'],
  mantle: [
    'https://mantle-rpc.publicnode.com',
    'https://mantle.drpc.org',
    'https://mantle.api.onfinality.io/public',
  ],
  megaEth: ['https://megaeth.drpc.org'],
  mode: ['https://mode.drpc.org'],
  monad: [
    'https://monad-mainnet.drpc.org',
    'https://rpc-mainnet.monadinfra.com',
    'https://rpc1.monad.xyz',
    'https://rpc3.monad.xyz',
  ],
  plasma: ['https://plasma.drpc.org', 'https://plasma.api.onfinality.io/public'],
  plume: ['https://plume.drpc.org', 'https://plume-mainnet.gateway.tatum.io'],
  scroll: [
    'https://scroll-rpc.publicnode.com',
    'https://scroll.drpc.org',
    'https://scroll.api.onfinality.io/public',
  ],
  sei: ['https://sei.drpc.org'],
  soneium: ['https://soneium.drpc.org'],
  sonic: [
    'https://sonic-rpc.publicnode.com',
    'https://sonic.drpc.org',
    'https://sonic.api.onfinality.io/public',
  ],
  story: [],
  unichain: [
    'https://unichain-rpc.publicnode.com',
    'https://unichain.drpc.org',
    'https://unichain.api.onfinality.io/public',
    'https://unichain-mainnet.gateway.tatum.io',
  ],
  worldChain: ['https://worldchain.drpc.org'],
  zkSyncEra: ['https://zksync.drpc.org', 'https://zksync.api.onfinality.io/public'],
} as const
