export const FALLBACK_RPC_URLS = {
  ethereum: ['https://eth.drpc.org', 'https://ethereum-rpc.publicnode.com'],
  bsc: ['https://bsc.drpc.org', 'https://bsc-rpc.publicnode.com'],
  avalanche: ['https://avalanche.drpc.org', 'https://avalanche-c-chain-rpc.publicnode.com'],
  arbitrum: ['https://arbitrum.drpc.org', 'https://arbitrum-one-rpc.publicnode.com'],
  optimism: ['https://optimism.drpc.org', 'https://optimism-rpc.publicnode.com'],
  gnosis: ['https://gnosis.drpc.org', 'https://gnosis-rpc.publicnode.com'],
  polygon: ['https://polygon.drpc.org', 'https://polygon-bor-rpc.publicnode.com'],
  base: ['https://base.drpc.org', 'https://base-rpc.publicnode.com'],
  monad: ['https://monad-mainnet.drpc.org', 'https://rpc.monad.xyz'],
  hyperEvm: ['https://hyperliquid.drpc.org', 'https://rpc.hyperliquid.xyz/evm'],
  plasma: ['https://plasma.drpc.org', 'https://rpc.plasma.to'],
  plume: ['https://plume.drpc.org', 'https://rpc.plume.org'],
  mantle: ['https://mantle.drpc.org', 'https://mantle-rpc.publicnode.com'],
  ink: ['https://ink.drpc.org', 'https://rpc-gel.inkonchain.com', 'https://rpc-qnd.inkonchain.com'],
  megaEth: ['https://megaeth.drpc.org', 'https://mainnet.megaeth.com/rpc'],
  berachain: ['https://berachain.drpc.org', 'https://berachain-rpc.publicnode.com'],
  scroll: ['https://scroll.drpc.org', 'https://scroll-rpc.publicnode.com'],
  cronos: ['https://cronos.drpc.org', 'https://cronos-evm-rpc.publicnode.com'],
  flowEvm: ['https://mainnet.evm.nodes.onflow.org'],
  celo: ['https://celo.drpc.org', 'https://forno.celo.org'],
  katana: ['https://katana.drpc.org', 'https://rpc.katana.network'],
  story: ['https://mainnet.storyrpc.io'],
  zkSyncEra: ['https://zksync.drpc.org', 'https://mainnet.era.zksync.io'],
  blast: ['https://blast.drpc.org', 'https://rpc.blast.io'],
  worldChain: ['https://worldchain.drpc.org', 'https://worldchain-mainnet.g.alchemy.com/public'],
  hemi: ['https://hemi.drpc.org', 'https://rpc.hemi.network/rpc'],
  linea: ['https://linea.drpc.org', 'https://linea-rpc.publicnode.com'],
  sonic: ['https://sonic.drpc.org', 'https://sonic-rpc.publicnode.com'],
  unichain: ['https://unichain.drpc.org', 'https://unichain-rpc.publicnode.com'],
  bob: ['https://bob.drpc.org', 'https://rpc.gobob.xyz'],
  mode: ['https://mode.drpc.org', 'https://mainnet.mode.network'],
  soneium: ['https://soneium.drpc.org', 'https://rpc.soneium.org'],
  abstract: ['https://rpc.ankr.com/abstract'],
} as const
