export const PUBLIC_RPC_URLS = {
  // first class chains
  ethereum: ['https://ethereum-rpc.publicnode.com', 'https://eth.drpc.org'],
  bsc: ['https://bsc-rpc.publicnode.com', 'https://bsc.drpc.org'],
  avalanche: ['https://avalanche-c-chain-rpc.publicnode.com', 'https://avalanche.drpc.org'],
  arbitrum: ['https://arbitrum-one-rpc.publicnode.com', 'https://arbitrum.drpc.org'],
  optimism: ['https://optimism-rpc.publicnode.com', 'https://optimism.drpc.org'],
  gnosis: ['https://gnosis-rpc.publicnode.com', 'https://gnosis.drpc.org'],
  polygon: ['https://polygon-bor-rpc.publicnode.com', 'https://polygon.drpc.org'],
  base: ['https://base-rpc.publicnode.com', 'https://base.drpc.org'],
  // second class chains
  abstract: [
    'https://api.mainnet.abs.xyz',
    'https://abstract.drpc.org',
    'https://abstract.api.onfinality.io/public',
    'https://abstract-mainnet.gateway.tatum.io',
  ],
  berachain: [
    'https://rpc.berachain.com',
    'https://berachain-rpc.publicnode.com',
    'https://berachain.drpc.org',
    'https://berachain-mainnet.gateway.tatum.io',
  ],
  blast: ['https://rpc.blast.io', 'https://blast-rpc.publicnode.com', 'https://blast.drpc.org'],
  bob: ['https://rpc.gobob.xyz', 'https://bob.drpc.org'],
  celo: [
    'https://forno.celo.org',
    'https://celo.drpc.org',
    'https://celo.api.onfinality.io/public',
    'https://celo-mainnet.gateway.tatum.io',
  ],
  cronos: [
    'https://evm.cronos.org',
    'https://cronos-evm-rpc.publicnode.com',
    'https://cronos.drpc.org',
    'https://cro-mainnet.gateway.tatum.io',
  ],
  ethereal: ['https://rpc.ethereal.trade'],
  flowEvm: ['https://mainnet.evm.nodes.onflow.org', 'https://flow-mainnet.gateway.tatum.io'],
  hemi: ['https://rpc.hemi.network/rpc', 'https://hemi.drpc.org'],
  hyperEvm: ['https://rpc.hyperliquid.xyz/evm', 'https://hyperliquid.drpc.org'],
  ink: [
    'https://rpc-gel.inkonchain.com',
    'https://rpc-qnd.inkonchain.com',
    'https://ink.drpc.org',
  ],
  katana: [
    'https://rpc.katana.network',
    'https://rpc.katanarpc.com',
    'https://katana.drpc.org',
  ],
  linea: [
    'https://rpc.linea.build',
    'https://linea-rpc.publicnode.com',
    'https://linea.drpc.org',
  ],
  mantle: [
    'https://rpc.mantle.xyz',
    'https://mantle-rpc.publicnode.com',
    'https://mantle.drpc.org',
    'https://mantle.api.onfinality.io/public',
  ],
  megaEth: ['https://mainnet.megaeth.com/rpc', 'https://megaeth.drpc.org'],
  mode: ['https://mainnet.mode.network', 'https://mode.drpc.org'],
  monad: [
    'https://rpc.monad.xyz',
    'https://monad-mainnet.drpc.org',
    'https://rpc-mainnet.monadinfra.com',
    'https://rpc1.monad.xyz',
    'https://rpc3.monad.xyz',
  ],
  plasma: [
    'https://rpc.plasma.to',
    'https://plasma.drpc.org',
    'https://plasma.api.onfinality.io/public',
  ],
  plume: [
    'https://rpc.plume.org',
    'https://plume.drpc.org',
    'https://plume-mainnet.gateway.tatum.io',
  ],
  scroll: [
    'https://rpc.scroll.io',
    'https://scroll-rpc.publicnode.com',
    'https://scroll.drpc.org',
    'https://scroll.api.onfinality.io/public',
  ],
  sei: ['https://evm-rpc.sei-apis.com', 'https://sei.drpc.org'],
  soneium: ['https://rpc.soneium.org', 'https://soneium.drpc.org'],
  sonic: [
    'https://rpc.soniclabs.com',
    'https://sonic-rpc.publicnode.com',
    'https://sonic.drpc.org',
    'https://sonic.api.onfinality.io/public',
  ],
  story: ['https://mainnet.storyrpc.io'],
  unichain: [
    'https://mainnet.unichain.org',
    'https://unichain-rpc.publicnode.com',
    'https://unichain.drpc.org',
    'https://unichain.api.onfinality.io/public',
    'https://unichain-mainnet.gateway.tatum.io',
  ],
  worldChain: ['https://worldchain-mainnet.g.alchemy.com/public', 'https://worldchain.drpc.org'],
  zkSyncEra: [
    'https://mainnet.era.zksync.io',
    'https://zksync.drpc.org',
    'https://zksync.api.onfinality.io/public',
  ],
} as const
