name: Bounty
description: Create a bounty
labels: ["bounty"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bounty
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: General background needed for bounty hunter to complete task
      placeholder: We want a new widget on the dashboard that displays fancy things.
    validations:
      required: true
  - type: textarea
    id: reference
    attributes:
      label: Reference
      description: An explanation as to where the bounty hunter should look or code that is affected
      placeholder: It may be useful to start by looking at `Dashboard.tsx`
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: The criteria that needs to be completed in order for the bounty to be considered complete
      placeholder: The widget displays correctly on the dashboard as per the mockups.
    validations:
      required: true
  - type: textarea
    id: screenshots-or-mockups
    attributes:
      label: Screenshots/Mockups
      description: Screenshots related to UI changes for simple changes, links to clickable mockups for larger features
      placeholder: Only include screenshots or mockups for features that require UI changes.
    validations:
      required: false
  - type: checkboxes
    id: cross-team
    attributes:
      label: Cross team
      description: My bounty requires and I will add the tag(s)
      options:
        - label: needs engineering
        - label: needs product
  - type: textarea
    id: bounty-hunters
    attributes:
      label: Bounty Hunters
      description: Information for bounty hunters to join ShapeShift discord and other general information (this can be left as it is)
      value: |
        - [Join our discord](https://discord.gg/shapeshift)
        - Include an expected timeline for you to complete work in the work plan when you apply for this bounty!
        - Please refer to [this link](https://shapeshiftdao.gitbook.io/getting-started/how-to-contribute/bounties#resources-for-new-contributors-and-bounty-hunters) for some basic info
    validations:
      required: false
