blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/shapeshift
    about: Join our discord
  - name: Shapeshift Fourms
    url: https://forum.shapeshift.com/
    about: Join our fourms
