// @ts-nocheck
/* tslint:disable */
/* eslint-disable */
/**
 * Jupiter API v6
 * The core of [jup.ag](https://jup.ag). Easily get a quote and swap through Jupiter API.  ### Rate Limit We update our rate limit from time to time depending on the load of our servers. We recommend running your own instance of the API if you want to have high rate limit, here to learn how to run the [self-hosted API](https://station.jup.ag/docs/apis/self-hosted).  ### API Wrapper - Typescript [@jup-ag/api](https://github.com/jup-ag/jupiter-quote-api-node)  ### Data types - Public keys are base58 encoded strings - raw data such as Vec<u8\\> are base64 encoded strings 
 *
 * The version of the OpenAPI document: 6.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SwapInfo
 */
export interface SwapInfo {
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    ammKey: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    inputMint: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    outputMint: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    inAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    outAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    feeAmount: string;
    /**
     * 
     * @type {string}
     * @memberof SwapInfo
     */
    feeMint: string;
}

/**
 * Check if a given object implements the SwapInfo interface.
 */
export function instanceOfSwapInfo(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ammKey" in value;
    isInstance = isInstance && "inputMint" in value;
    isInstance = isInstance && "outputMint" in value;
    isInstance = isInstance && "inAmount" in value;
    isInstance = isInstance && "outAmount" in value;
    isInstance = isInstance && "feeAmount" in value;
    isInstance = isInstance && "feeMint" in value;

    return isInstance;
}

export function SwapInfoFromJSON(json: any): SwapInfo {
    return SwapInfoFromJSONTyped(json, false);
}

export function SwapInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SwapInfo {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ammKey': json['ammKey'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'inputMint': json['inputMint'],
        'outputMint': json['outputMint'],
        'inAmount': json['inAmount'],
        'outAmount': json['outAmount'],
        'feeAmount': json['feeAmount'],
        'feeMint': json['feeMint'],
    };
}

export function SwapInfoToJSON(value?: SwapInfo | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ammKey': value.ammKey,
        'label': value.label,
        'inputMint': value.inputMint,
        'outputMint': value.outputMint,
        'inAmount': value.inAmount,
        'outAmount': value.outAmount,
        'feeAmount': value.feeAmount,
        'feeMint': value.feeMint,
    };
}
