// This is a Jest-friendly stub for use while testing. It will be swapped out for webpack.ts during build. See
// react-app-rewired.config.js for details.

// eslint-disable-next-line import/no-default-export
// export default Object.fromEntries(
//   Object.entries(process.env).filter(([k]) => k.startsWith('REACT_APP_')),
// )

const env = {
  REACT_APP_FEATURE_OSMOSIS_LP: 'false',
  REACT_APP_FEATURE_OSMOSIS_LP_ADDITIONAL_POOLS: 'false',
  REACT_APP_FEATURE_PENDO: 'false',
  REACT_APP_FEATURE_AXELAR: 'false',
  REACT_APP_FEATURE_YEARN: 'false',
  REACT_APP_FEATURE_WHEREVER: 'true',
  REACT_APP_FEATURE_YAT: 'true',
  REACT_APP_FEATURE_COWSWAP: 'true',
  REACT_APP_FEATURE_OSMOSIS_SEND: 'true',
  REACT_APP_FEATURE_OSMOSIS_STAKING: 'true',
  REACT_APP_FEATURE_OSMOSIS_SWAP: 'true',
  REACT_APP_FEATURE_OPTIMISM: 'true',
  REACT_APP_FEATURE_OPTIMISM_ZRX: 'true',
  REACT_APP_FEATURE_SAVERS_VAULTS: 'true',
  REACT_APP_FEATURE_WALLET_CONNECT_TO_DAPPS: 'true',
  REACT_APP_FEATURE_WALLET_CONNECT_TO_DAPPS_V2: 'true',
  REACT_APP_FEATURE_IDLE: 'true',
  REACT_APP_FEATURE_THOR_SWAP: 'true',
  REACT_APP_FEATURE_TRADE_RATES: 'false',
  REACT_APP_FEATURE_ARKEO_AIRDROP: 'true',
  REACT_APP_FEATURE_CONSENT_BANNER: 'true',
  REACT_APP_FEATURE_MIXPANEL: 'false',
  REACT_APP_LOG_LEVEL: 'debug',
  REACT_APP_PORTIS_DAPP_ID: '8609e6a8-e0dc-45e6-a0ad-edde63a4cdda',
  REACT_APP_WALLET_MIGRATION_URL: 'https://wallets.shapeshift.com/api/migrate',
  REACT_APP_FRIENDLY_CAPTCHA_SITE_KEY: 'FCMM7AFC0S6A8NUK',
  REACT_APP_KEEPKEY_VERSIONS_URL:
    'https://raw.githack.com/keepkey/keepkey-updater/master/firmware/releases.json',
  REACT_APP_COWSWAP_HTTP_URL: 'https://api.cow.fi/mainnet/api',
  REACT_APP_ALCHEMY_POLYGON_URL:
    'https://polygon-mainnet.g.alchemy.com/v2/458rwsHQDajSOTCdC5AACXQUMYrllacR',
  REACT_APP_GEM_COINIFY_SUPPORTED_COINS:
    'https://api.gem.co/institutions/coinify/supported_currencies',
  REACT_APP_GEM_WYRE_SUPPORTED_COINS: 'https://api.gem.co/institutions/wyre/supported_currencies',
  REACT_APP_GEM_ENV: 'production',
  REACT_APP_GEM_API_KEY: 'bb4164a72246dae1e03010d664d6cdae4e19b2554de02e3bf6c3cd30aa7e359e',
  REACT_APP_TOKEMAK_STATS_URL: 'https://stats.tokemaklabs.com/',
  REACT_APP_COINGECKO_API_KEY: 'CG-we5Z4KbdYMCgMUVAqDjQMWfc',
  REACT_APP_ALCHEMY_API_KEY: '3DnVf4ZoxBk0W0TZcipqAhmATm7uc1vE',
  REACT_APP_JUNOPAY_APP_ID: 'live_SYkQkrlyIQeuQf8AauSOaGTa',
  REACT_APP_JUNOPAY_ASSET_LOGO_URL: 'https://cdn.juno.finance/',
  REACT_APP_JUNOPAY_BASE_API_URL: 'https://api.juno.finance/',
  REACT_APP_JUNOPAY_BASE_APP_URL: 'https://juno.finance/partners/shapeshift/',
  REACT_APP_BOARDROOM_API_BASE_URL: 'https://api.boardroom.info/v1/protocols/shapeshift/',
  REACT_APP_BOARDROOM_APP_BASE_URL: 'https://boardroom.io/shapeshift/',
  REACT_APP_SNAPSHOT_BASE_URL: 'https://snapshot.org/#/shapeshiftdao.eth',
  REACT_APP_MTPELERIN_ASSETS_API: 'https://api.mtpelerin.com/currencies/tokens',
  REACT_APP_MTPELERIN_BUY_URL: 'https://buy.mtpelerin.com/',
  REACT_APP_MTPELERIN_SELL_URL: 'https://sell.mtpelerin.com/',
  REACT_APP_MTPELERIN_REFERRAL_CODE: 'shapeshift',
  REACT_APP_ONRAMPER_WIDGET_URL: 'https://widget.onramper.com/',
  REACT_APP_ONRAMPER_API_URL: 'https://onramper.tech/',
  REACT_APP_ONRAMPER_API_KEY: 'pk_prod_ViOib9FcqKQeqqBsLF6ZPYis8X0Wdl9ma16rBhTxXmw0',
  REACT_APP_YAT_NODE_URL: 'https://a.y.at',
  REACT_APP_KEEPKEY_UPDATER_RELEASE_PAGE:
    'https://github.com/keepkey/keepkey-updater/releases/latest',
  REACT_APP_KEEPKEY_DESKTOP_URL: 'http://localhost:1646/',
  REACT_APP_KEEPKEY_UPDATER_BASE_URL:
    'https://github.com/keepkey/keepkey-updater/releases/download/v2.1.4/',
  REACT_APP_ETHERSCAN_API_KEY: 'XT8BI6VDYUGD9675X861ATHZNK3AN6HRMF',
  REACT_APP_WHEREVER_PARTNER_KEY: '00da1f18-3bba-4b71-824c-21e5ed772dfa',
  REACT_APP_OSMOSIS_LCD_BASE_URL: 'https://daemon.osmosis.shapeshift.com/',
  REACT_APP_OSMOSIS_POOL_PAGINATION_LIMIT: '1000',
  REACT_APP_OSMOSIS_IMPERATOR_BASE_URL: 'https://api-osmosis.imperator.co/',
  REACT_APP_OSMOSIS_ALLOW_LOW_LIQUIDITY_POOLS: 'true',
  REACT_APP_WALLET_CONNECT_PROJECT_ID: '5abef0455c768644c2bc866f1520374f',
  REACT_APP_WALLET_CONNECT_RELAY_URL: 'wss://relay.walletconnect.com',
  REACT_APP_PENDO_API_KEY: '67c2f326-a6c2-4aa2-4559-08a53b679e93',
  REACT_APP_PENDO_CONSENT_VERSION: 'v1',
  REACT_APP_PENDO_SUB_ID: '6047664892149760',
  REACT_APP_PENDO_VISITOR_ID_PREFIX: 'test_visitor',
  REACT_APP_PENDO_UNSAFE_DESIGNER_MODE: 'false',
  REACT_APP_UNCHAINED_ETHEREUM_HTTP_URL: 'https://dev-api.ethereum.shapeshift.com',
  REACT_APP_UNCHAINED_ETHEREUM_WS_URL: 'wss://dev-api.ethereum.shapeshift.com',
  REACT_APP_UNCHAINED_AVALANCHE_HTTP_URL: 'https://dev-api.avalanche.shapeshift.com',
  REACT_APP_UNCHAINED_AVALANCHE_WS_URL: 'wss://dev-api.avalanche.shapeshift.com',
  REACT_APP_UNCHAINED_OPTIMISM_HTTP_URL: 'https://dev-api.optimism.shapeshift.com',
  REACT_APP_UNCHAINED_OPTIMISM_WS_URL: 'wss://dev-api.optimism.shapeshift.com',
  REACT_APP_UNCHAINED_BITCOIN_HTTP_URL: 'https://dev-api.bitcoin.shapeshift.com',
  REACT_APP_UNCHAINED_BITCOIN_WS_URL: 'wss://dev-api.bitcoin.shapeshift.com',
  REACT_APP_UNCHAINED_DOGECOIN_WS_URL: 'wss://dev-api.dogecoin.shapeshift.com',
  REACT_APP_UNCHAINED_DOGECOIN_HTTP_URL: 'https://dev-api.dogecoin.shapeshift.com',
  REACT_APP_UNCHAINED_LITECOIN_WS_URL: 'wss://dev-api.litecoin.shapeshift.com',
  REACT_APP_UNCHAINED_LITECOIN_HTTP_URL: 'https://dev-api.litecoin.shapeshift.com',
  REACT_APP_UNCHAINED_BITCOINCASH_HTTP_URL: 'https://dev-api.bitcoincash.shapeshift.com',
  REACT_APP_UNCHAINED_BITCOINCASH_WS_URL: 'wss://dev-api.bitcoincash.shapeshift.com',
  REACT_APP_UNCHAINED_COSMOS_HTTP_URL: 'https://dev-api.cosmos.shapeshift.com',
  REACT_APP_UNCHAINED_COSMOS_WS_URL: 'wss://dev-api.cosmos.shapeshift.com',
  REACT_APP_UNCHAINED_OSMOSIS_HTTP_URL: 'https://dev-api.osmosis.shapeshift.com',
  REACT_APP_UNCHAINED_OSMOSIS_WS_URL: 'wss://dev-api.osmosis.shapeshift.com',
  REACT_APP_UNCHAINED_THORCHAIN_HTTP_URL: 'https://dev-api.thorchain.shapeshift.com',
  REACT_APP_UNCHAINED_THORCHAIN_WS_URL: 'wss://dev-api.thorchain.shapeshift.com',
  REACT_APP_ETHEREUM_NODE_URL: 'https://dev-daemon.ethereum.shapeshift.com',
  REACT_APP_ETHEREUM_INFURA_URL: 'https://mainnet.infura.io/v3/fb05c87983c4431baafd4600fd33de7e',
  REACT_APP_AVALANCHE_NODE_URL: 'https://dev-daemon.avalanche.shapeshift.com/ext/bc/C/rpc',
  REACT_APP_OPTIMISM_NODE_URL: 'https://dev-daemon.optimism.shapeshift.com',
  REACT_APP_COSMOS_NODE_URL: 'https://dev-daemon.cosmos.shapeshift.com',
  REACT_APP_OSMOSIS_NODE_URL: 'https://dev-daemon.osmosis.shapeshift.com',
  REACT_APP_THORCHAIN_NODE_URL: 'https://dev-daemon.thorchain.shapeshift.com',
  REACT_APP_MIDGARD_URL: 'https://dev-indexer.thorchain.shapeshift.com/v2',
  REACT_APP_FEATURE_COSMOS_SDK_OPPORTUNITIES_ABSTRACTION: 'true',
}

export default env
