import type { ChainId } from '@shapeshiftoss/caip'
import {
  arbitrumChainId,
  avalancheChainId,
  baseChainId,
  blastChainId,
  berachainChainId,
  bobChainId,
  bscChainId,
  cronosChainId,
  ethChainId,
  gnosisChainId,
  hemiChainId,
  inkChainId,
  katanaChainId,
  lineaChainId,
  mantleChainId,
  modeChainId,
  monadChainId,
  optimismChainId,
  plasmaChainId,
  polygonChainId,
  solanaChainId,
  storyChainId,
  soneiumChainId,
  sonicChainId,
  suiChainId,
  tronChainId,
  zkSyncEraChainId,
  worldChainChainId,
  unichainChainId,
} from '@shapeshiftoss/caip'

export const ZERION_CHAINS = [
  // shapeshift supported
  'avalanche',
  'binance-smart-chain',
  'ethereum',
  'optimism',
  'polygon',
  'arbitrum',
  'xdai',
  'base',
  'solana',
  'tron',
  'monad',
  'sui',
  'plasma',
  'world-chain',
  'katana',
  'story',
  'zksync-era',
  'blast',
  'hemi',
  'mantle',
  'linea',
  'berachain',
  'ink',
  'cronos',
  'sonic',
  'unichain',
  'bob',
  'mode',
  'soneium',
  // not yet
  // 'aurora',
  // 'fantom',
] as const

export type ZerionChainId = (typeof ZERION_CHAINS)[number]

export const ZERION_CHAINS_MAP: Record<ZerionChainId, ChainId> = {
  avalanche: avalancheChainId,
  'binance-smart-chain': bscChainId,
  ethereum: ethChainId,
  optimism: optimismChainId,
  polygon: polygonChainId,
  arbitrum: arbitrumChainId,
  xdai: gnosisChainId,
  base: baseChainId,
  solana: solanaChainId,
  tron: tronChainId,
  monad: monadChainId,
  sui: suiChainId,
  plasma: plasmaChainId,
  'world-chain': worldChainChainId,
  katana: katanaChainId,
  story: storyChainId,
  'zksync-era': zkSyncEraChainId,
  blast: blastChainId,
  hemi: hemiChainId,
  mantle: mantleChainId,
  linea: lineaChainId,
  berachain: berachainChainId,
  ink: inkChainId,
  cronos: cronosChainId,
  sonic: sonicChainId,
  unichain: unichainChainId,
  bob: bobChainId,
  mode: modeChainId,
  soneium: soneiumChainId,
}

export const zerionChainIdToChainId = (chainId: ZerionChainId): ChainId | undefined =>
  ZERION_CHAINS_MAP[chainId]
