interface ImportMetaEnv {
  // Feature flags - present in all envs
  readonly VITE_FEATURE_BNBSMARTCHAIN: string
  readonly VITE_FEATURE_POLYGON: string
  readonly VITE_FEATURE_GNOSIS: string
  readonly VITE_FEATURE_ARBITRUM: string
  readonly VITE_FEATURE_ARBITRUM_NOVA: string
  readonly VITE_FEATURE_SOLANA: string
  readonly VITE_FEATURE_BASE: string
  readonly VITE_FEATURE_MAYACHAIN: string
  readonly VITE_FEATURE_OPTIMISM: string
  readonly VITE_FEATURE_MIXPANEL: string
  readonly VITE_ENABLE_ADDRESSABLE: string
  readonly VITE_FEATURE_SAVERS_VAULTS: string
  readonly VITE_FEATURE_SAVERS_VAULTS_DEPOSIT: string
  readonly VITE_FEATURE_SAVERS_VAULTS_WITHDRAW: string
  readonly VITE_FEATURE_WALLET_CONNECT_TO_DAPPS_V2: string
  readonly VITE_FEATURE_WALLET_CONNECT_TO_DAPPS: string
  readonly VITE_FEATURE_CHATWOOT: string
  readonly VITE_FEATURE_ADVANCED_SLIPPAGE: string
  readonly VITE_FEATURE_LEDGER_WALLET: string
  readonly VITE_FEATURE_VULTISIG_WALLET: string
  readonly VITE_FEATURE_WALLET_CONNECT_V2: string
  readonly VITE_FEATURE_THORCHAIN_LENDING: string
  readonly VITE_FEATURE_THORCHAIN_LENDING_BORROW: string
  readonly VITE_FEATURE_THORCHAIN_LENDING_REPAY: string
  readonly VITE_FEATURE_THORCHAINSWAP_LONGTAIL: string
  readonly VITE_FEATURE_THORCHAINSWAP_L1_TO_LONGTAIL: string
  readonly VITE_FEATURE_THORCHAIN_LP: string
  readonly VITE_FEATURE_THORCHAIN_LP_DEPOSIT: string
  readonly VITE_FEATURE_THORCHAIN_LP_WITHDRAW: string
  readonly VITE_FEATURE_ACCOUNT_MANAGEMENT: string
  readonly VITE_FEATURE_ACCOUNT_MANAGEMENT_LEDGER: string
  readonly VITE_FEATURE_RFOX: string
  readonly VITE_FEATURE_RFOX_LP: string
  readonly VITE_FEATURE_ARBITRUM_BRIDGE: string
  readonly VITE_FEATURE_CUSTOM_TOKEN_IMPORT: string
  readonly VITE_FEATURE_USDT_APPROVAL_RESET: string
  readonly VITE_FEATURE_PORTALS_SWAPPER: string
  readonly VITE_FEATURE_RUNEPOOL: string
  readonly VITE_FEATURE_RUNEPOOL_DEPOSIT: string
  readonly VITE_FEATURE_RUNEPOOL_WITHDRAW: string
  readonly VITE_FEATURE_MARKETS: string
  readonly VITE_FEATURE_FOX_PAGE: string
  readonly VITE_FEATURE_FOX_PAGE_RFOX: string
  readonly VITE_FEATURE_FOX_PAGE_FOX_SECTION: string
  readonly VITE_FEATURE_FOX_PAGE_FOX_FARMING_SECTION: string
  readonly VITE_FEATURE_FOX_PAGE_GOVERNANCE: string
  readonly VITE_FEATURE_PHANTOM_WALLET: string
  readonly VITE_FEATURE_LIMIT_ORDERS: string
  readonly VITE_FEATURE_NEW_WALLET_FLOW: string
  readonly VITE_FEATURE_NEW_LIMIT_FLOW: string
  readonly VITE_FEATURE_THORCHAIN_SWAPPER_ACK: string
  readonly VITE_FEATURE_DYNAMIC_LP_ASSETS: string
  readonly VITE_FEATURE_READ_ONLY_ASSETS: string
  readonly VITE_FEATURE_SWAPPER_SOLANA: string
  readonly VITE_FEATURE_CHAINFLIP_SWAP: string
  readonly VITE_FEATURE_CHAINFLIP_SWAP_DCA: string
  readonly VITE_FEATURE_COWSWAP: string
  readonly VITE_FEATURE_THOR_SWAP: string
  readonly VITE_FEATURE_ZRX_SWAP: string
  readonly VITE_FEATURE_JUPITER_SWAP: string
  readonly VITE_FEATURE_SWAPPER_RELAY: string
  readonly VITE_FEATURE_MAYA_SWAP: string
  readonly VITE_FEATURE_BUTTERSWAP: string
  readonly VITE_FEATURE_SWAPPER_FIAT_RAMPS: string

  // URLs and API keys from base .env (always defined)
  readonly VITE_ABSOLUTE_URL_PREFIX: string
  readonly VITE_CHATWOOT_TOKEN: string
  readonly VITE_CHATWOOT_URL: string
  readonly VITE_LOG_LEVEL: string
  readonly VITE_REDUX_WINDOW: string
  readonly VITE_WALLET_MIGRATION_URL: string
  readonly VITE_FRIENDLY_CAPTCHA_SITE_KEY: string
  readonly VITE_KEEPKEY_VERSIONS_URL: string
  readonly VITE_KEEPKEY_LATEST_RELEASE_URL: string
  readonly VITE_COWSWAP_BASE_URL: string
  readonly VITE_ALCHEMY_POLYGON_URL: string
  readonly VITE_TOKEMAK_STATS_URL: string
  readonly VITE_COINCAP_API_KEY: string
  readonly VITE_EXCHANGERATEHOST_BASE_URL: string
  readonly VITE_EXCHANGERATEHOST_API_KEY: string
  readonly VITE_ALCHEMY_API_KEY: string
  readonly VITE_MORALIS_API_KEY: string
  readonly VITE_ALCHEMY_SOLANA_BASE_URL: string
  readonly VITE_BOARDROOM_API_BASE_URL: string
  readonly VITE_BOARDROOM_APP_BASE_URL: string
  readonly VITE_SNAPSHOT_BASE_URL: string
  readonly VITE_MTPELERIN_ASSETS_API: string
  readonly VITE_MTPELERIN_BUY_URL: string
  readonly VITE_MTPELERIN_SELL_URL: string
  readonly VITE_MTPELERIN_REFERRAL_CODE: string
  readonly VITE_MTPELERIN_INTEGRATION_KEY: string
  readonly VITE_BANXA_API_URL: string
  readonly VITE_BANXA_API_KEY: string
  readonly VITE_ONRAMPER_WIDGET_URL: string
  readonly VITE_ONRAMPER_API_URL: string
  readonly VITE_ONRAMPER_API_KEY: string
  readonly VITE_ADDRESSABLE_TID: string
  readonly VITE_YAT_NODE_URL: string
  readonly VITE_KEEPKEY_UPDATER_RELEASE_PAGE: string
  readonly VITE_KEEPKEY_DESKTOP_URL: string
  readonly VITE_KEEPKEY_UPDATER_BASE_URL: string
  readonly VITE_ETHERSCAN_API_KEY: string
  readonly VITE_WALLET_CONNECT_TO_DAPPS_PROJECT_ID: string
  readonly VITE_WALLET_CONNECT_WALLET_PROJECT_ID: string
  readonly VITE_WALLET_CONNECT_RELAY_URL: string
  readonly VITE_PORTALS_BASE_URL: string
  readonly VITE_SNAP_ID: string
  readonly VITE_SNAP_VERSION: string
  readonly VITE_EXPERIMENTAL_CUSTOM_SEND_NONCE: string
  readonly VITE_SENTRY_DSN_URL: string
  readonly VITE_ZERION_BASE_URL: string
  readonly VITE_ZRX_BASE_URL: string
  readonly VITE_CHAINFLIP_API_KEY: string
  readonly VITE_CHAINFLIP_API_URL: string
  readonly VITE_NEAR_INTENTS_API_KEY: string
  readonly VITE_FEATURE_NEAR_INTENTS_SWAP: string
  readonly VITE_RELAY_API_URL: string
  readonly VITE_TENDERLY_ACCOUNT_SLUG: string
  readonly VITE_TENDERLY_PROJECT_SLUG: string
  readonly VITE_TENDERLY_API_KEY: string
  readonly VITE_FEATURE_ADDRESS_BOOK: string

  // Unchained URLs and node URLs - present in all envs (prod, development, private)
  // even though they're not present in base env
  readonly VITE_UNCHAINED_ETHEREUM_HTTP_URL: string
  readonly VITE_UNCHAINED_ETHEREUM_WS_URL: string
  readonly VITE_UNCHAINED_AVALANCHE_HTTP_URL: string
  readonly VITE_UNCHAINED_AVALANCHE_WS_URL: string
  readonly VITE_UNCHAINED_OPTIMISM_HTTP_URL: string
  readonly VITE_UNCHAINED_OPTIMISM_WS_URL: string
  readonly VITE_UNCHAINED_BNBSMARTCHAIN_HTTP_URL: string
  readonly VITE_UNCHAINED_BNBSMARTCHAIN_WS_URL: string
  readonly VITE_UNCHAINED_POLYGON_HTTP_URL: string
  readonly VITE_UNCHAINED_POLYGON_WS_URL: string
  readonly VITE_UNCHAINED_GNOSIS_HTTP_URL: string
  readonly VITE_UNCHAINED_GNOSIS_WS_URL: string
  readonly VITE_UNCHAINED_ARBITRUM_HTTP_URL: string
  readonly VITE_UNCHAINED_ARBITRUM_WS_URL: string
  readonly VITE_UNCHAINED_ARBITRUM_NOVA_HTTP_URL: string
  readonly VITE_UNCHAINED_ARBITRUM_NOVA_WS_URL: string
  readonly VITE_UNCHAINED_BASE_HTTP_URL: string
  readonly VITE_UNCHAINED_BASE_WS_URL: string
  readonly VITE_UNCHAINED_BITCOIN_HTTP_URL: string
  readonly VITE_UNCHAINED_BITCOIN_WS_URL: string
  readonly VITE_UNCHAINED_DOGECOIN_WS_URL: string
  readonly VITE_UNCHAINED_DOGECOIN_HTTP_URL: string
  readonly VITE_UNCHAINED_LITECOIN_WS_URL: string
  readonly VITE_UNCHAINED_LITECOIN_HTTP_URL: string
  readonly VITE_UNCHAINED_BITCOINCASH_HTTP_URL: string
  readonly VITE_UNCHAINED_BITCOINCASH_WS_URL: string
  readonly VITE_UNCHAINED_COSMOS_HTTP_URL: string
  readonly VITE_UNCHAINED_COSMOS_WS_URL: string
  readonly VITE_UNCHAINED_THORCHAIN_HTTP_URL: string
  readonly VITE_UNCHAINED_THORCHAIN_WS_URL: string
  readonly VITE_UNCHAINED_THORCHAIN_V1_HTTP_URL: string
  readonly VITE_UNCHAINED_MAYACHAIN_HTTP_URL: string
  readonly VITE_UNCHAINED_MAYACHAIN_WS_URL: string
  readonly VITE_UNCHAINED_SOLANA_HTTP_URL: string
  readonly VITE_UNCHAINED_SOLANA_WS_URL: string
  readonly VITE_ETHEREUM_NODE_URL: string
  readonly VITE_AVALANCHE_NODE_URL: string
  readonly VITE_OPTIMISM_NODE_URL: string
  readonly VITE_BNBSMARTCHAIN_NODE_URL: string
  readonly VITE_POLYGON_NODE_URL: string
  readonly VITE_GNOSIS_NODE_URL: string
  readonly VITE_ARBITRUM_NODE_URL: string
  readonly VITE_ARBITRUM_NOVA_NODE_URL: string
  readonly VITE_BASE_NODE_URL: string
  readonly VITE_THORCHAIN_NODE_URL: string
  readonly VITE_MAYACHAIN_NODE_URL: string
  readonly VITE_SOLANA_NODE_URL: string
  readonly VITE_THORCHAIN_MIDGARD_URL: string
  readonly VITE_MAYACHAIN_MIDGARD_URL: string
  readonly VITE_SWAPS_SERVER_URL: string
  readonly VITE_NOTIFICATIONS_SERVER_URL: string
  readonly VITE_USER_SERVER_URL: string
  readonly VITE_FEATURE_NOTIFICATIONS_WEBSERVICES: string

  // Only present in *some* envs
  readonly VITE_MIXPANEL_TOKEN?: string

  // Local development only - enables Sentry on localhost
  readonly VITE_ENABLE_SENTRY_LOCALHOST?: string
}

interface ImportMeta {
  readonly env: ImportMetaEnv
}
