import type { Csp } from '../../types'

const REACT_APP_KEEPKEY_VERSIONS_URL = process.env.REACT_APP_KEEPKEY_VERSIONS_URL
const REACT_APP_KEEPKEY_DESKTOP_URL = process.env.REACT_APP_KEEPKEY_DESKTOP_URL

if (!REACT_APP_KEEPKEY_VERSIONS_URL) throw new Error('REACT_APP_KEEPKEY_VERSIONS_URL is required')
if (!REACT_APP_KEEPKEY_DESKTOP_URL) throw new Error('REACT_APP_KEEPKEY_DESKTOP_URL is required')

export const csp: Csp = {
  'connect-src': [REACT_APP_KEEPKEY_VERSIONS_URL, REACT_APP_KEEPKEY_DESKTOP_URL],
}
